/**
 * AI-art skins: new games that reuse a template's math 1:1 (reskin) with painted artwork generated by
 * scripts/gen-ai-art.js (OpenAI Images) and imported by scripts/import-ai-art.py.
 *
 * A skin appears in the catalog only once its artwork is imported (public/games/<id>/assets/stage.json).
 *
 *   KINDS[kind]   what a template needs: the pictures to generate and which symbol each piece becomes
 *   SKINS         one entry per game: theme, scene for the prompts, and the name of every symbol
 */

/** Pictures + slicing plan per template kind. `sheet` lists symbol ids in reading order. */
const KINDS = {
  megaways: {
    template: 'jaguar_temple_megaways',
    cabinet: 'a single tall rectangular reel window for 6 columns and 7 rows of symbols (slightly taller than wide)',
    sheets: [{ file: 'symbols', grid: '5 columns x 2 rows', ids: ['WILD', 'SCATTER', 'JAGUAR', 'IDOL', 'SERPENT', 'EAGLE', 'JADE', 'RUBY', 'TOPAZ', 'SAPPHIRE'] }]
  },
  clusters: {
    template: 'sweet_spot_mania',
    cabinet: 'a single square reel window for a 7 x 7 grid of symbols',
    sheets: [{ file: 'symbols', grid: '4 columns x 2 rows', ids: ['SCATTER', 'CUPCAKE', 'DONUT', 'CHOCO', 'RED', 'ORANGE', 'GREEN', 'BLUE'] }]
  },
  holdwin: {
    template: 'wolf_moon_holdwin',
    cabinet: 'a single wide rectangular reel window for 5 reels and 3 rows of symbols',
    sheets: [{ file: 'symbols', grid: '5 columns x 2 rows', ids: ['WILD', 'BISON', 'BEAR', 'EAGLE', 'DEER', 'A', 'K', 'Q', 'J', '10'] }]
  },
  matchlines: {
    template: 'gold_rush_canyon',
    cabinet: 'a single rectangular reel window for 7 columns and 8 rows of symbols (a bit taller than wide)',
    sheets: [{ file: 'symbols', grid: '4 columns x 3 rows', ids: ['WILD', 'SCATTER', 'SHERIFF', 'HORSE', 'BOOTS', 'GOLD', 'A', 'K', 'Q', 'J', '10', '9'] }]
  },
  titans: {
    template: 'tiki_titans',
    cabinet: 'an EMPTY reel area shaped like a stepped diamond: 7 vertical windows of equal width, 2, 4, 5, 6, 5, 4 and 2 cells tall, each centered vertically',
    windows: [2, 4, 5, 6, 5, 4, 2],
    strip: true, // tall Wild pillar
    card: true, // 3-row giant portrait card
    sheets: [
      { file: 'symbols', grid: '3 columns x 3 rows', ids: ['SCATTER', 'TURTLE', 'PARROT', 'SHELL', 'PINEAPPLE', 'WILD', 'SHARK', '_spare1', '_spare2'] },
      { file: 'cards', grid: 'A K Q in the top row, J and 10 in the bottom row', ids: ['A', 'K', 'Q', 'J', '10'] }
    ]
  }
};

/** Asset file of a symbol piece (templates keep their own names). */
function assetName(kind, id) {
  if (kind === 'titans' && id === 'WILD') return 'wild_icon.png';
  if (kind === 'titans' && id === 'SHARK') return 'shark_icon.png';
  return `sym_${id.toLowerCase()}.png`;
}

// look: accent, bg1, bg2, font, particles · scene: background for the cabinet prompt · sym: symbol names (by template id)
const S = (id, kind, name, category, look, scene, sym, extra = {}) => ({ id, kind, name, category, look, scene, sym, ...extra });
const L = (accent, bg1, bg2, font, particles) => ({ accent, bg1, bg2, font, particles });

const SKINS = [
  // ------------------------------------------------------------------ Megaways
  S('dragon_pearl_megaways', 'megaways', 'Dragon Pearl Megaways', 'asian', L('#ffcf3a', '#5a0a0a', '#1a0202', 'Cinzel', 'embers'), 'a Chinese imperial palace on misty mountains at night with red lanterns and a golden dragon in the clouds',
    { WILD: 'Golden Dragon Wild', SCATTER: 'Dragon Pearl', JAGUAR: 'Red Dragon', IDOL: 'Jade Emperor Statue', SERPENT: 'Golden Koi', EAGLE: 'Fortune Lantern', JADE: 'Jade Coin', RUBY: 'Ruby Knot', TOPAZ: 'Gold Ingot', SAPPHIRE: 'Blue Porcelain Vase' }),
  S('pharaoh_tomb_megaways', 'megaways', "Pharaoh's Tomb Megaways", 'egypt', L('#ffd23f', '#3a2a08', '#0e0802', 'Cinzel', 'dust'), 'the inside of a golden pharaoh tomb lit by torches, hieroglyph walls and treasure',
    { WILD: 'Golden Pharaoh Mask Wild', SCATTER: 'Pyramid', JAGUAR: 'Anubis Jackal', IDOL: 'Eye of Ra', SERPENT: 'Cobra Sphinx', EAGLE: 'Eye of Horus', JADE: 'Scarab Emerald', RUBY: 'Ankh Ruby', TOPAZ: 'Canopic Jar', SAPPHIRE: 'Lapis Lotus' }),
  S('viking_raid_megaways', 'megaways', 'Viking Raid Megaways', 'norse', L('#8fd0ff', '#123048', '#040c14', 'Russo One', 'snow'), 'a snowy fjord with viking longships, northern lights and a wooden longhouse',
    { WILD: 'Rune Shield Wild', SCATTER: 'Longship', JAGUAR: 'Viking Chief', IDOL: 'Battle Axe', SERPENT: 'Sea Serpent', EAGLE: 'Raven', JADE: 'Emerald Rune', RUBY: 'Ruby Rune', TOPAZ: 'Amber Rune', SAPPHIRE: 'Ice Rune' }),
  S('atlantis_deep_megaways', 'megaways', 'Atlantis Deep Megaways', 'ocean', L('#3de8ff', '#063a52', '#010c14', 'Cinzel', 'bubbles'), 'the sunken city of Atlantis deep under the sea, glowing marble ruins, coral and light rays',
    { WILD: 'Trident Wild', SCATTER: 'Golden Seashell Temple', JAGUAR: 'Sea King', IDOL: 'Mermaid', SERPENT: 'Kraken', EAGLE: 'Seahorse', JADE: 'Sea Emerald', RUBY: 'Coral Ruby', TOPAZ: 'Golden Pearl', SAPPHIRE: 'Aqua Crystal' }),
  S('samurai_honor_megaways', 'megaways', 'Samurai Honor Megaways', 'asian', L('#ff5a6a', '#3a0a18', '#0c0206', 'Cinzel', 'petals'), 'a Japanese castle at sunset with blooming sakura trees and a red torii gate',
    { WILD: 'Katana Wild', SCATTER: 'Torii Gate', JAGUAR: 'Samurai Warrior', IDOL: 'Oni Mask', SERPENT: 'Water Dragon', EAGLE: 'Golden Crane', JADE: 'Jade Fan', RUBY: 'Red Lantern', TOPAZ: 'Gold Koban', SAPPHIRE: 'Blue Kabuto' }),
  S('wild_buffalo_megaways', 'megaways', 'Wild Buffalo Megaways', 'animals', L('#ffb03a', '#4a2808', '#120802', 'Rye', 'dust'), 'the great prairie at golden sunset with canyons and a stampede of buffalo in the distance',
    { WILD: 'Sunset Wild', SCATTER: 'Golden Buffalo Coin', JAGUAR: 'Buffalo', IDOL: 'Mountain Lion', SERPENT: 'Rattlesnake', EAGLE: 'Bald Eagle', JADE: 'Turquoise Stone', RUBY: 'Red Jasper', TOPAZ: 'Amber Nugget', SAPPHIRE: 'River Sapphire' }),
  S('galactic_gems_megaways', 'megaways', 'Galactic Gems Megaways', 'space', L('#c77dff', '#1a0a3a', '#04020c', 'Orbitron', 'stars'), 'deep space with a glowing nebula, planets and a futuristic space station',
    { WILD: 'Black Hole Wild', SCATTER: 'Supernova', JAGUAR: 'Astronaut', IDOL: 'Alien', SERPENT: 'Rocket', EAGLE: 'Ringed Planet', JADE: 'Green Star Crystal', RUBY: 'Red Star Crystal', TOPAZ: 'Solar Crystal', SAPPHIRE: 'Blue Star Crystal' }),
  S('inferno_devil_megaways', 'megaways', 'Inferno Devil Megaways', 'horror', L('#ff4a1a', '#3a0602', '#0c0100', 'Creepster', 'embers'), 'a fiery underworld with lava rivers, black obsidian towers and a burning throne',
    { WILD: 'Devil Horns Wild', SCATTER: 'Burning Skull', JAGUAR: 'Demon Lord', IDOL: 'Hellhound', SERPENT: 'Fire Serpent', EAGLE: 'Lava Bat', JADE: 'Poison Gem', RUBY: 'Blood Ruby', TOPAZ: 'Fire Opal', SAPPHIRE: 'Soul Sapphire' }),
  S('rainforest_rumble_megaways', 'megaways', 'Rainforest Rumble Megaways', 'jungle', L('#6aff5a', '#0a3a18', '#020c04', 'Bangers', 'leaves'), 'a lush rainforest with giant waterfalls, vines, ancient stone ruins and morning light',
    { WILD: 'Gorilla King Wild', SCATTER: 'Waterfall Idol', JAGUAR: 'Gorilla', IDOL: 'Toucan', SERPENT: 'Anaconda', EAGLE: 'Jungle Python', JADE: 'Leaf Emerald', RUBY: 'Orchid Ruby', TOPAZ: 'Banana Gold', SAPPHIRE: 'Morpho Sapphire' }),
  S('lucky_leprechaun_megaways', 'megaways', 'Lucky Leprechaun Megaways', 'lucky', L('#3ddc5a', '#0a3a14', '#020c04', 'Lobster', 'sparkle'), 'green Irish hills with a rainbow ending in a pot of gold, stone cottages and clover fields',
    { WILD: 'Rainbow Wild', SCATTER: 'Pot of Gold', JAGUAR: 'Leprechaun', IDOL: 'Golden Harp', SERPENT: 'Magic Hat', EAGLE: 'Horseshoe', JADE: 'Four-Leaf Clover', RUBY: 'Red Mushroom', TOPAZ: 'Gold Coin', SAPPHIRE: 'Blue Bell Flower' }),

  // ------------------------------------------------------------------ Cluster pays
  S('fruit_frenzy_clusters', 'clusters', 'Fruit Frenzy Clusters', 'fruits', L('#ff4a6a', '#5a0a2a', '#14020a', 'Fredoka', 'sparkle'), 'a sunny tropical fruit market with colorful stalls and juice splashes',
    { SCATTER: 'Golden Watermelon', CUPCAKE: 'Strawberry', DONUT: 'Pineapple Slice', CHOCO: 'Grapes', RED: 'Cherry', ORANGE: 'Orange', GREEN: 'Lime', BLUE: 'Blueberry' }),
  S('ocean_bubbles_clusters', 'clusters', 'Ocean Bubbles Clusters', 'ocean', L('#3de8ff', '#063a5a', '#010c18', 'Fredoka', 'bubbles'), 'a bright coral reef underwater with sun rays and cute sea life',
    { SCATTER: 'Treasure Chest', CUPCAKE: 'Clownfish', DONUT: 'Octopus', CHOCO: 'Sea Turtle', RED: 'Red Starfish', ORANGE: 'Orange Shell', GREEN: 'Green Sea Glass', BLUE: 'Blue Pearl' }),
  S('crystal_cavern_clusters', 'clusters', 'Crystal Cavern Clusters', 'gems', L('#c77dff', '#2a0a4a', '#08020e', 'Cinzel', 'sparkle'), 'a magical underground cave full of giant glowing crystals and an underground lake',
    { SCATTER: 'Crystal Skull', CUPCAKE: 'Diamond', DONUT: 'Crown Crystal', CHOCO: 'Magic Geode', RED: 'Ruby Shard', ORANGE: 'Amber Shard', GREEN: 'Emerald Shard', BLUE: 'Sapphire Shard' }),
  S('space_jelly_clusters', 'clusters', 'Space Jelly Clusters', 'space', L('#ff7ab8', '#1a0a3a', '#04020c', 'Fredoka', 'stars'), 'a cute cartoon galaxy with candy-colored planets and a jelly spaceship',
    { SCATTER: 'Jelly UFO', CUPCAKE: 'Alien Jelly', DONUT: 'Planet Donut', CHOCO: 'Rocket Pop', RED: 'Red Jelly Star', ORANGE: 'Orange Jelly Moon', GREEN: 'Green Jelly Comet', BLUE: 'Blue Jelly Orb' }),
  S('halloween_treats_clusters', 'clusters', 'Halloween Treats Clusters', 'horror', L('#ff8a1a', '#2a0a3a', '#08020c', 'Creepster', 'embers'), 'a spooky Halloween night with a haunted house, jack-o-lanterns, full moon and bats',
    { SCATTER: 'Witch Cauldron', CUPCAKE: 'Jack-o-Lantern', DONUT: 'Ghost Candy', CHOCO: 'Spider Cookie', RED: 'Blood Candy', ORANGE: 'Candy Corn', GREEN: 'Slime Drop', BLUE: 'Poison Potion' }),
  S('christmas_cookies_clusters', 'clusters', 'Christmas Cookies Clusters', 'holiday', L('#ff3a4a', '#0a3a1a', '#020c06', 'Lobster', 'snow'), 'a cozy snowy Christmas village with a glowing tree, gifts and a gingerbread house',
    { SCATTER: 'Santa Bag', CUPCAKE: 'Gingerbread Man', DONUT: 'Candy Cane', CHOCO: 'Hot Cocoa', RED: 'Red Ornament', ORANGE: 'Golden Bell', GREEN: 'Holly Cookie', BLUE: 'Snowflake Cookie' }),
  S('jungle_juice_clusters', 'clusters', 'Jungle Juice Clusters', 'jungle', L('#ffd23f', '#0a4a1a', '#020e04', 'Bangers', 'leaves'), 'a bright cartoon jungle with a waterfall, tiki bar and tropical flowers',
    { SCATTER: 'Coconut Cocktail', CUPCAKE: 'Monkey', DONUT: 'Toucan', CHOCO: 'Banana Bunch', RED: 'Red Hibiscus', ORANGE: 'Mango', GREEN: 'Kiwi', BLUE: 'Blue Passion Fruit' }),
  S('neon_arcade_clusters', 'clusters', 'Neon Arcade Clusters', 'fun', L('#3dffe0', '#1a0a3a', '#04020c', 'Orbitron', 'neon'), 'a retro 80s neon arcade hall with glowing machines and a synthwave sunset grid',
    { SCATTER: 'Golden Joystick', CUPCAKE: 'Pixel Hero', DONUT: 'Retro Ghost', CHOCO: 'Game Cartridge', RED: 'Red Pixel Heart', ORANGE: 'Orange Coin', GREEN: 'Green Mushroom Pixel', BLUE: 'Blue Diamond Pixel' }),
  S('magic_potions_clusters', 'clusters', 'Magic Potions Clusters', 'fantasy', L('#b45cff', '#2a0a3a', '#08020c', 'Cinzel', 'sparkle'), 'a wizard alchemy laboratory with bubbling cauldrons, spell books and floating candles',
    { SCATTER: 'Crystal Ball', CUPCAKE: 'Spell Book', DONUT: 'Magic Mushroom', CHOCO: 'Owl Familiar', RED: 'Red Potion', ORANGE: 'Orange Potion', GREEN: 'Green Potion', BLUE: 'Blue Potion' }),
  S('sweet_bakery_clusters', 'clusters', 'Sweet Bakery Clusters', 'sweets', L('#ff7ab8', '#5a1a3a', '#14040c', 'Fredoka', 'sparkle'), 'a pastel French bakery with cakes on stands, macarons and a pink shop window',
    { SCATTER: 'Wedding Cake', CUPCAKE: 'Croissant', DONUT: 'Eclair', CHOCO: 'Cheesecake', RED: 'Raspberry Macaron', ORANGE: 'Peach Macaron', GREEN: 'Pistachio Macaron', BLUE: 'Blueberry Macaron' }),

  // ------------------------------------------------------------------ Hold & Win
  S('dragon_coins_holdwin', 'holdwin', 'Dragon Coins Hold & Win', 'asian', L('#ffcf3a', '#5a0a0a', '#1a0202', 'Cinzel', 'embers'), 'a red Chinese temple courtyard at night with lanterns and fireworks',
    { WILD: 'Dragon Wild', COIN: 'Dragon Coin', BISON: 'Golden Dragon', BEAR: 'Tiger', EAGLE: 'Koi Fish', DEER: 'Lucky Cat' }, { jackpots: { MINI: 'BRONZE', MINOR: 'SILVER', MAJOR: 'GOLD', GRAND: 'EMPEROR' } }),
  S('buffalo_gold_holdwin', 'holdwin', 'Buffalo Gold Hold & Win', 'animals', L('#ffb03a', '#4a2808', '#120802', 'Rye', 'dust'), 'a red rock canyon at sunset with a lone mesa and prairie grass',
    { WILD: 'Sunset Wild', COIN: 'Gold Buffalo Coin', BISON: 'Buffalo', BEAR: 'Mountain Lion', EAGLE: 'Bald Eagle', DEER: 'Elk' }, { jackpots: { MINI: 'COPPER', MINOR: 'SILVER', MAJOR: 'GOLD', GRAND: 'STAMPEDE' } }),
  S('pharaoh_fortune_holdwin', 'holdwin', "Pharaoh's Fortune Hold & Win", 'egypt', L('#ffd23f', '#3a2a08', '#0e0802', 'Cinzel', 'dust'), 'the Nile at night with glowing pyramids and a golden temple',
    { WILD: 'Pharaoh Wild', COIN: 'Scarab Coin', BISON: 'Pharaoh', BEAR: 'Cleopatra Queen', EAGLE: 'Anubis', DEER: 'Golden Cat Statue' }, { jackpots: { MINI: 'BRONZE', MINOR: 'SILVER', MAJOR: 'GOLD', GRAND: 'PHARAOH' } }),
  S('pirate_doubloons_holdwin', 'holdwin', 'Pirate Doubloons Hold & Win', 'pirates', L('#ffcf3a', '#0d3b4f', '#03121a', 'Pirata One', 'dust'), 'a pirate ship deck at night with a treasure island and a stormy moonlit sea',
    { WILD: 'Jolly Roger Wild', COIN: 'Doubloon', BISON: 'Pirate Captain', BEAR: 'Parrot', EAGLE: 'Treasure Chest', DEER: 'Ship Wheel' }, { jackpots: { MINI: 'COPPER', MINOR: 'SILVER', MAJOR: 'GOLD', GRAND: 'KRAKEN' } }),
  S('lucky_lion_holdwin', 'holdwin', 'Lucky Lion Hold & Win', 'animals', L('#ffcf3a', '#5a2a08', '#140802', 'Russo One', 'sparkle'), 'the African savanna at golden hour with acacia trees and Pride Rock-like cliffs',
    { WILD: 'Lion King Wild', COIN: 'Sun Coin', BISON: 'Lion', BEAR: 'Elephant', EAGLE: 'Rhino', DEER: 'Zebra' }, { jackpots: { MINI: 'BRONZE', MINOR: 'SILVER', MAJOR: 'GOLD', GRAND: 'KING' } }),
  S('viking_silver_holdwin', 'holdwin', 'Viking Silver Hold & Win', 'norse', L('#cfe8ff', '#123048', '#040c14', 'Russo One', 'snow'), 'a viking mead hall with a roaring fire, shields on the walls and snow outside',
    { WILD: 'Valkyrie Wild', COIN: 'Silver Rune Coin', BISON: 'Viking Warrior', BEAR: 'War Bear', EAGLE: 'Raven', DEER: 'Wolf' }, { jackpots: { MINI: 'IRON', MINOR: 'SILVER', MAJOR: 'GOLD', GRAND: 'VALHALLA' } }),
  S('panda_fortune_holdwin', 'holdwin', 'Panda Fortune Hold & Win', 'asian', L('#3ddc5a', '#0a3a1a', '#020c06', 'Cinzel', 'petals'), 'a misty bamboo forest with a small pagoda and a moonlit pond',
    { WILD: 'Panda Wild', COIN: 'Jade Coin', BISON: 'Giant Panda', BEAR: 'Red Panda', EAGLE: 'Crane', DEER: 'Bamboo Temple' }, { jackpots: { MINI: 'BRONZE', MINOR: 'JADE', MAJOR: 'GOLD', GRAND: 'FORTUNE' } }),
  S('aztec_sun_holdwin', 'holdwin', 'Aztec Sun Gold Hold & Win', 'aztec', L('#ffcf3a', '#0a3a2a', '#020c08', 'Cinzel', 'leaves'), 'an Aztec step pyramid in the jungle at sunrise with a giant golden sun stone',
    { WILD: 'Sun Stone Wild', COIN: 'Aztec Gold Coin', BISON: 'Jaguar Warrior', BEAR: 'Quetzalcoatl', EAGLE: 'Eagle Knight', DEER: 'Jade Mask' }, { jackpots: { MINI: 'JADE', MINOR: 'SILVER', MAJOR: 'GOLD', GRAND: 'SUN GOD' } }),
  S('fire_phoenix_holdwin', 'holdwin', 'Fire Phoenix Hold & Win', 'fantasy', L('#ff7a1a', '#4a0a02', '#140200', 'Cinzel', 'embers'), 'a volcanic mountain temple engulfed in golden flames under a red sky',
    { WILD: 'Phoenix Wild', COIN: 'Fire Coin', BISON: 'Phoenix', BEAR: 'Fire Dragon', EAGLE: 'Flame Crown', DEER: 'Lava Egg' }, { jackpots: { MINI: 'EMBER', MINOR: 'FLAME', MAJOR: 'BLAZE', GRAND: 'PHOENIX' } }),
  S('tiger_treasure_holdwin', 'holdwin', 'Tiger Treasure Hold & Win', 'asian', L('#ffb03a', '#4a1a08', '#140602', 'Russo One', 'leaves'), 'a jungle temple ruin in Asia overgrown with vines at dusk, golden statues',
    { WILD: 'White Tiger Wild', COIN: 'Tiger Coin', BISON: 'Bengal Tiger', BEAR: 'Golden Buddha Statue', EAGLE: 'Elephant', DEER: 'Lotus Flower' }, { jackpots: { MINI: 'BRONZE', MINOR: 'SILVER', MAJOR: 'GOLD', GRAND: 'TIGER' } }),

  // ------------------------------------------------------------------ Line cascades (match lines)
  S('pirate_plunder_lines', 'matchlines', 'Pirate Plunder Lines', 'pirates', L('#ffcf3a', '#0d3b4f', '#03121a', 'Pirata One', 'dust'), 'a pirate cove with a galleon, treasure caves and a tropical sunset',
    { WILD: 'Cannon Wild', SCATTER: 'Treasure Map', SHERIFF: 'Pirate Captain', HORSE: 'Parrot', BOOTS: 'Rum Barrel', GOLD: 'Treasure Chest' }),
  S('arctic_expedition_lines', 'matchlines', 'Arctic Expedition Lines', 'winter', L('#8fd0ff', '#0a2a4a', '#020a14', 'Russo One', 'snow'), 'a frozen arctic landscape with icebergs, northern lights and an explorer camp',
    { WILD: 'Ice Crystal Wild', SCATTER: 'Compass', SHERIFF: 'Polar Bear', HORSE: 'Husky', BOOTS: 'Penguin', GOLD: 'Frozen Treasure' }),
  S('egyptian_sands_lines', 'matchlines', 'Egyptian Sands Lines', 'egypt', L('#ffd23f', '#3a2a08', '#0e0802', 'Cinzel', 'dust'), 'the desert with the great pyramids and the sphinx under a golden sunset',
    { WILD: 'Ankh Wild', SCATTER: 'Pyramid', SHERIFF: 'Pharaoh', HORSE: 'Camel', BOOTS: 'Scarab', GOLD: 'Golden Mask' }),
  S('candy_carnival_lines', 'matchlines', 'Candy Carnival Lines', 'candy', L('#ff7ab8', '#5a1a3a', '#14040c', 'Fredoka', 'sparkle'), 'a candy carnival with a ferris wheel, cotton candy clouds and lollipop trees',
    { WILD: 'Candy Bomb Wild', SCATTER: 'Carnival Ticket', SHERIFF: 'Clown Cupcake', HORSE: 'Cotton Candy', BOOTS: 'Candy Apple', GOLD: 'Gumball Machine' }),
  S('space_miners_lines', 'matchlines', 'Space Miners Lines', 'space', L('#3dffe0', '#0a1a3a', '#02040c', 'Orbitron', 'stars'), 'an asteroid mining base with glowing ore, a red planet and space trucks',
    { WILD: 'Plasma Drill Wild', SCATTER: 'Space Station', SHERIFF: 'Space Miner', HORSE: 'Mining Robot', BOOTS: 'Rover', GOLD: 'Glowing Ore' }),
  S('enchanted_forest_lines', 'matchlines', 'Enchanted Forest Lines', 'fantasy', L('#6aff9a', '#0a3a2a', '#020c08', 'Cinzel', 'sparkle'), 'a magical forest with glowing mushrooms, a fairy tree house and fireflies',
    { WILD: 'Fairy Wild', SCATTER: 'Magic Tree', SHERIFF: 'Unicorn', HORSE: 'Owl', BOOTS: 'Fox', GOLD: 'Magic Acorn' }),
  S('ancient_rome_lines', 'matchlines', 'Ancient Rome Lines', 'ancient', L('#ffcf3a', '#4a0a0a', '#140202', 'Cinzel', 'dust'), 'the Colosseum at sunset with marble columns and red banners',
    { WILD: 'Golden Eagle Standard Wild', SCATTER: 'Colosseum', SHERIFF: 'Gladiator', HORSE: 'Chariot Horse', BOOTS: 'Roman Helmet', GOLD: 'Gold Laurel' }),
  S('fiesta_mexicana_lines', 'matchlines', 'Fiesta Mexicana Lines', 'fun', L('#ff5a3a', '#4a1a08', '#140602', 'Bangers', 'sparkle'), 'a colorful Mexican town square during a fiesta with papel picado and a mariachi stage',
    { WILD: 'Pinata Wild', SCATTER: 'Sombrero', SHERIFF: 'Mariachi', HORSE: 'Chili Pepper', BOOTS: 'Maracas', GOLD: 'Taco' }),
  S('cyber_city_lines', 'matchlines', 'Cyber City Lines', 'scifi', L('#ff3ad8', '#1a0a3a', '#04020c', 'Orbitron', 'neon'), 'a cyberpunk megacity at night with neon signs, flying cars and rain',
    { WILD: 'Neon Chip Wild', SCATTER: 'Hologram Core', SHERIFF: 'Cyber Hacker', HORSE: 'Android', BOOTS: 'Drone', GOLD: 'Data Cube' }),
  S('dragon_kingdom_lines', 'matchlines', 'Dragon Kingdom Lines', 'fantasy', L('#ffb03a', '#3a0a2a', '#0c0208', 'Cinzel', 'embers'), 'a medieval castle on a cliff with dragons flying around a stormy sky',
    { WILD: 'Dragon Egg Wild', SCATTER: 'Castle', SHERIFF: 'Dragon', HORSE: 'Knight', BOOTS: 'Princess Crown', GOLD: 'Dragon Hoard' }),

  // ------------------------------------------------------------------ Titans (like Tiki Titans)
  S('aztec_titans', 'titans', 'Aztec Titans', 'aztec', L('#ffcf3a', '#0a3a2a', '#020c08', 'Cinzel', 'leaves'), 'an Aztec jungle with a step pyramid, waterfalls and a golden sun at dawn',
    { WILD: 'Jaguar Totem Wild', SHARK: 'Feathered Serpent God', SCATTER: 'Sun Stone', TURTLE: 'Jaguar', PARROT: 'Quetzal Bird', SHELL: 'Jade Mask', PINEAPPLE: 'Cacao Pod' }),
  S('viking_titans', 'titans', 'Viking Titans', 'norse', L('#8fd0ff', '#123048', '#040c14', 'Russo One', 'snow'), 'a snowy viking fjord with longships, northern lights and a stone circle',
    { WILD: 'Runestone Pillar Wild', SHARK: 'Thunder Warrior', SCATTER: 'Longship', TURTLE: 'Viking Helmet', PARROT: 'Raven', SHELL: 'Drinking Horn', PINEAPPLE: 'Battle Axe' }),
  S('egypt_titans', 'titans', 'Egypt Titans', 'egypt', L('#ffd23f', '#3a2a08', '#0e0802', 'Cinzel', 'dust'), 'the Nile with pyramids and a giant golden temple under a starry night',
    { WILD: 'Obelisk Wild', SHARK: 'Anubis God', SCATTER: 'Pyramid', TURTLE: 'Scarab', PARROT: 'Falcon', SHELL: 'Canopic Jar', PINEAPPLE: 'Ankh' }),
  S('olympus_sky_titans', 'titans', 'Olympus Sky Titans', 'mythology', L('#ffe066', '#2a2a6a', '#08081c', 'Cinzel', 'clouds'), 'Mount Olympus above the clouds with a white marble temple and lightning',
    { WILD: 'Marble Column Wild', SHARK: 'Sky King God', SCATTER: 'Golden Temple', TURTLE: 'Pegasus', PARROT: 'Golden Eagle', SHELL: 'Amphora', PINEAPPLE: 'Laurel Wreath' }),
  S('dragon_titans', 'titans', 'Dragon Titans', 'asian', L('#ffcf3a', '#5a0a0a', '#1a0202', 'Cinzel', 'embers'), 'an ancient Chinese mountain temple in the clouds with red lanterns and waterfalls',
    { WILD: 'Jade Dragon Pillar Wild', SHARK: 'Golden Dragon', SCATTER: 'Dragon Pearl', TURTLE: 'Koi Fish', PARROT: 'Crane', SHELL: 'Lucky Cat', PINEAPPLE: 'Gold Ingot' }),
  S('ocean_titans', 'titans', 'Ocean Titans', 'ocean', L('#3de8ff', '#063a52', '#010c14', 'Cinzel', 'bubbles'), 'an underwater kingdom with coral castles, sun rays and giant kelp',
    { WILD: 'Coral Pillar Wild', SHARK: 'Kraken', SCATTER: 'Trident', TURTLE: 'Sea Turtle', PARROT: 'Seahorse', SHELL: 'Pearl Shell', PINEAPPLE: 'Starfish' }),
  S('jungle_titans', 'titans', 'Jungle Titans', 'jungle', L('#6aff5a', '#0a3a18', '#020c04', 'Bangers', 'leaves'), 'a deep jungle with a giant ancient tree, vines, ruins and fireflies',
    { WILD: 'Vine Totem Wild', SHARK: 'Gorilla King', SCATTER: 'Ancient Idol', TURTLE: 'Tiger', PARROT: 'Toucan', SHELL: 'Tree Frog', PINEAPPLE: 'Banana Bunch' }),
  S('frost_titans', 'titans', 'Frost Titans', 'winter', L('#bfe8ff', '#0a2a4a', '#020a14', 'Cinzel', 'snow'), 'a frozen ice kingdom with a crystal palace, glaciers and aurora sky',
    { WILD: 'Ice Pillar Wild', SHARK: 'Frost Giant', SCATTER: 'Ice Crown', TURTLE: 'Snow Owl', PARROT: 'Arctic Fox', SHELL: 'Ice Rune', PINEAPPLE: 'Snow Crystal' }),
  S('samurai_titans', 'titans', 'Samurai Titans', 'asian', L('#ff5a6a', '#3a0a18', '#0c0206', 'Cinzel', 'petals'), 'a Japanese mountain shrine with sakura trees, a red bridge and Mount Fuji',
    { WILD: 'Pagoda Pillar Wild', SHARK: 'Shogun Warrior', SCATTER: 'Torii Gate', TURTLE: 'Katana', PARROT: 'Crane', SHELL: 'Oni Mask', PINEAPPLE: 'Sake Bottle' }),
  S('inferno_titans', 'titans', 'Inferno Titans', 'horror', L('#ff4a1a', '#3a0602', '#0c0100', 'Creepster', 'embers'), 'a volcanic underworld with lava falls, obsidian spikes and a burning sky',
    { WILD: 'Lava Pillar Wild', SHARK: 'Demon Lord', SCATTER: 'Burning Skull', TURTLE: 'Hellhound', PARROT: 'Fire Bat', SHELL: 'Cursed Crown', PINEAPPLE: 'Soul Lantern' })
];

module.exports = { KINDS, SKINS, assetName };
