/**
 * Game skins — new games built on the 7 calibrated math templates.
 *
 * A skin re-uses the template's reels, paytable, features and RTP calibration
 * 1:1 and only replaces the look: symbols (icon + name + colour), title,
 * colours, frame, background scene, particles and font.
 *
 *   base   template id (pharaoh_riches | vegas_fruits | cyber_neon | olympus_thunder |
 *          sweet_sugar | jade_dragon | wild_safari)
 *   look   a: accent, b1/b2: background colours, rim: frame preset, sc: scene preset,
 *          p: particles, f: title font, med: medallion frames for high symbols,
 *          light: light reel background, t: [title line 1, title line 2]
 *   w / s  wild / scatter: [name, emoji, colour]  ('7' = classic seven, 'BAR' = bar plate)
 *   h      high symbols (replace the template's highs, same order = same pays)
 *   l      low symbols (optional — replaces royals / gems / low fruits)
 *   rc     royal letter colours (optional)
 *   gems   [[colour, shape], ...] recolour procedural gems (olympus base)
 *   m      multiplier glyph (tumble games)
 *
 * Symbol order in h / l is from highest to lowest paying.
 */

const sk = (base, id, name, cat, look, sym) => ({ base, id, name, cat, look, ...sym });

// ------------------------------------------------------------------ 20 lines 5x3 (pharaoh_riches)
const LINES20 = [
  sk('pharaoh_riches', 'aztec_sun', 'Aztec Sun Temple', 'aztec',
    { a: '#ffc233', b1: '#1f5130', b2: '#07170c', rim: 'gold', sc: 'pyramids', p: 'leaves', f: 'Cinzel', med: true },
    { w: ['Sun Wild', '☀️', '#ffc233'], s: ['Stone Idol', '🗿', '#9fb3a1'],
      h: [['Jaguar', '🐆', '#f0a030'], ['Macaw', '🦜', '#e8483f'], ['Serpent', '🐍', '#2fbf71'], ['Golden Corn', '🌽', '#ffd23f']] }),
  sk('pharaoh_riches', 'viking_valor', 'Viking Valor', 'norse',
    { a: '#9fd3ff', b1: '#2a3a52', b2: '#080d16', rim: 'silver', sc: 'mountains', p: 'snow', f: 'Cinzel', med: true },
    { w: ['Battle Axe', '🪓', '#9fd3ff'], s: ['Round Shield', '🛡️', '#d9a441'],
      h: [['Wolf', '🐺', '#b0bec5'], ['Bear', '🐻', '#a0704a'], ['Boar', '🐗', '#8d6e63'], ['Crossed Swords', '⚔️', '#cfd8dc']] }),
  sk('pharaoh_riches', 'pirate_bounty', "Pirate's Bounty", 'pirates',
    { a: '#ffcf4a', b1: '#0f3b57', b2: '#03101a', rim: 'bronze', sc: 'ocean', p: 'dust', f: 'Pirata One', med: true, t: ["PIRATE'S", 'BOUNTY'] },
    { w: ['Parrot Wild', '🦜', '#2fbf71'], s: ['Treasure Map', '🗺️', '#e8c46a'],
      h: [['Jolly Roger', '🏴‍☠️', '#37474f'], ['Anchor', '⚓', '#4a90c2'], ['Loot Bag', '💰', '#ffc233'], ['Dagger', '🗡️', '#cfd8dc']] }),
  sk('pharaoh_riches', 'samurai_honor', 'Samurai Honor', 'asian',
    { a: '#ff5a4f', b1: '#4a0d10', b2: '#110203', rim: 'ruby', sc: 'mountains', p: 'petals', f: 'Cinzel', med: true },
    { w: ['Tengu Wild', '👺', '#ff5a4f'], s: ['Torii Gate', '⛩️', '#ff7043'],
      h: [['Castle', '🏯', '#ffb74d'], ['Katana', '🗡️', '#cfd8dc'], ['Sake', '🍶', '#90caf9'], ['Wind Chime', '🎐', '#80deea']] }),
  sk('pharaoh_riches', 'dusty_gulch', 'Dusty Gulch', 'western',
    { a: '#ffb347', b1: '#7a3d12', b2: '#1c0b03', rim: 'bronze', sc: 'dunes', p: 'dust', f: 'Rye', med: true },
    { w: ['Cowboy Wild', '🤠', '#ffb347'], s: ['Stallion', '🐴', '#a1887f'],
      h: [['Mustang', '🐎', '#8d6e63'], ['Cactus', '🌵', '#43a047'], ['Whiskey', '🥃', '#ffa726'], ['Gold Coin', '🪙', '#ffd23f']] }),
  sk('pharaoh_riches', 'dragon_hoard', "Dragon's Hoard", 'fantasy',
    { a: '#ff7043', b1: '#4a1208', b2: '#120302', rim: 'gold', sc: 'castle', p: 'embers', f: 'Cinzel', med: true, t: ["DRAGON'S", 'HOARD'] },
    { w: ['Dragon Wild', '🐲', '#43a047'], s: ['Dragon Egg', '🥚', '#ffe0b2'],
      h: [['Crown', '👑', '#ffc233'], ['Diamond', '💎', '#4fc3f7'], ['Sword', '🗡️', '#cfd8dc'], ['Shield', '🛡️', '#8d6e63']] }),
  sk('pharaoh_riches', 'mermaid_pearls', 'Mermaid Pearls', 'ocean',
    { a: '#5ee7df', b1: '#0b4f6c', b2: '#02131c', rim: 'ice', sc: 'ocean', p: 'bubbles', f: 'Cinzel', med: true },
    { w: ['Mermaid Wild', '🧜‍♀️', '#5ee7df'], s: ['Pearl Shell', '🐚', '#ffccbc'],
      h: [['Dolphin', '🐬', '#4fc3f7'], ['Sea Turtle', '🐢', '#66bb6a'], ['Octopus', '🐙', '#ec407a'], ['Crab', '🦀', '#ff7043']] }),
  sk('pharaoh_riches', 'polar_treasures', 'Polar Treasures', 'winter',
    { a: '#b3e5fc', b1: '#1b4f72', b2: '#050f1a', rim: 'ice', sc: 'snow', p: 'snow', f: 'Cinzel', med: true },
    { w: ['Polar Bear', '🐻‍❄️', '#e1f5fe'], s: ['Snowflake', '❄️', '#81d4fa'],
      h: [['Penguin', '🐧', '#90a4ae'], ['Seal', '🦭', '#b0bec5'], ['Whale', '🐋', '#4fc3f7'], ['Fox', '🦊', '#ff8a50']] }),
  sk('pharaoh_riches', 'jungle_quest', 'Jungle Quest', 'jungle',
    { a: '#c6ff4a', b1: '#1b5e20', b2: '#041205', rim: 'emerald', sc: 'jungle', p: 'leaves', f: 'Bungee', med: true },
    { w: ['Gorilla Wild', '🦍', '#8d6e63'], s: ['Compass', '🧭', '#ffca28'],
      h: [['Tiger', '🐯', '#ffa726'], ['Toucan', '🦜', '#e53935'], ['Python', '🐍', '#7cb342'], ['Bananas', '🍌', '#ffee58']] }),
  sk('pharaoh_riches', 'galaxy_odyssey', 'Galaxy Odyssey', 'space',
    { a: '#8c9eff', b1: '#1a1446', b2: '#03020c', rim: 'amethyst', sc: 'space', p: 'stars', f: 'Orbitron', med: true },
    { w: ['Rocket Wild', '🚀', '#8c9eff'], s: ['Ringed Planet', '🪐', '#ffb74d'],
      h: [['Alien', '👽', '#76ff03'], ['UFO', '🛸', '#b0bec5'], ['Earth', '🌍', '#42a5f5'], ['Comet', '☄️', '#ff8a65']] }),
  sk('pharaoh_riches', 'haunted_manor', 'Haunted Manor', 'horror',
    { a: '#b2ff59', b1: '#2a1440', b2: '#07030d', rim: 'obsidian', sc: 'graveyard', p: 'embers', f: 'Creepster', med: true },
    { w: ['Vampire Wild', '🧛', '#e53935'], s: ['Jack-o-Lantern', '🎃', '#ff9800'],
      h: [['Ghost', '👻', '#eceff1'], ['Bat', '🦇', '#7e57c2'], ['Skull', '💀', '#e0e0e0'], ['Candle', '🕯️', '#ffcc80']] }),
  sk('pharaoh_riches', 'clover_gold', 'Lucky Clover Gold', 'lucky',
    { a: '#7cff6b', b1: '#145a2a', b2: '#031208', rim: 'emerald', sc: 'hills', p: 'sparkle', f: 'Cinzel', med: true },
    { w: ['Clover Wild', '🍀', '#7cff6b'], s: ['Rainbow', '🌈', '#ffeb3b'],
      h: [['Top Hat', '🎩', '#43a047'], ['Pint', '🍺', '#ffb300'], ['Gold Coin', '🪙', '#ffd23f'], ['Sheep', '🐑', '#eeeeee']] }),
  sk('pharaoh_riches', 'glory_of_rome', 'Glory of Rome', 'ancient',
    { a: '#ffd54f', b1: '#5b1414', b2: '#140404', rim: 'gold', sc: 'columns', p: 'dust', f: 'Cinzel', med: true, t: ['GLORY OF', 'ROME'] },
    { w: ['Temple Wild', '🏛️', '#ffd54f'], s: ['Colosseum', '🏟️', '#bcaaa4'],
      h: [['Lion', '🦁', '#ffb300'], ['Chariot Horse', '🐎', '#8d6e63'], ['Amphora', '🏺', '#d9774a'], ['Grapes', '🍇', '#8e24aa']] }),
  sk('pharaoh_riches', 'gold_mine_rush', 'Gold Mine Rush', 'adventure',
    { a: '#ffca28', b1: '#3e2716', b2: '#0d0704', rim: 'bronze', sc: 'volcano', p: 'embers', f: 'Rye', med: true },
    { w: ['Dynamite', '🧨', '#e53935'], s: ['Pickaxe', '⛏️', '#b0bec5'],
      h: [['Diamond', '💎', '#4fc3f7'], ['Gold Coin', '🪙', '#ffd23f'], ['Lantern', '🔦', '#ffb300'], ['Ore Rock', '🪨', '#9e9e9e']] }),
  sk('pharaoh_riches', 'bastet_blessing', "Bastet's Blessing", 'egypt',
    { a: '#c39bff', b1: '#2b1b4a', b2: '#08040f', rim: 'amethyst', sc: 'pyramids', p: 'sparkle', f: 'Cinzel', med: true, t: ["BASTET'S", 'BLESSING'] },
    { w: ['Cat Goddess', '🐈‍⬛', '#c39bff'], s: ['Crescent Moon', '🌙', '#fff59d'],
      h: [['Scarab', '🪲', '#26c6da'], ['Cobra', '🐍', '#66bb6a'], ['Canopic Jar', '🏺', '#d9774a'], ['Sacred Eye', '👁️', '#90caf9']] })
];

// ------------------------------------------------------------------ classic 3x3 (vegas_fruits)
const CLASSIC = [
  sk('vegas_fruits', 'pepper_fiesta', 'Pepper Fiesta 7s', 'classic',
    { a: '#ff3d00', b1: '#5a1300', b2: '#140300', rim: 'ruby', sc: 'sunburst', p: 'embers', f: 'Bungee', light: true, t: ['PEPPER', 'FIESTA 7s'] },
    { w: ['Hot 7', '7', '#ff3d00'], s: ['Fire', '🔥', '#ff9100'],
      h: [['BAR', 'BAR', '#222'], ['Chili', '🌶️', '#e53935'], ['Taco', '🌮', '#ffb300'], ['Avocado', '🥑', '#7cb342']],
      l: [['Tomato', '🍅', '#e53935'], ['Corn', '🌽', '#ffd23f'], ['Onion', '🧅', '#ce93d8'], ['Lemon', '🍋', '#f5d400']] }),
  sk('vegas_fruits', 'diamond_deluxe', 'Diamond Deluxe', 'classic',
    { a: '#4fc3f7', b1: '#0d2748', b2: '#020814', rim: 'silver', sc: 'marquee', p: 'sparkle', f: 'Bungee', light: true },
    { w: ['Blue 7', '7', '#1e88e5'], s: ['Star', '⭐', '#ffc933'],
      h: [['Diamond', '💎', '#4fc3f7'], ['Crown', '👑', '#ffc233'], ['BAR', 'BAR', '#222'], ['Ring', '💍', '#b0bec5']],
      l: [['Bell', '🔔', '#f0a500'], ['Coin', '🪙', '#ffd23f'], ['Cherry', '🍒', '#e3212b'], ['Lemon', '🍋', '#f5d400']] }),
  sk('vegas_fruits', 'neon_nights', 'Neon Nights 777', 'classic',
    { a: '#ff2bd6', b1: '#2a0a3a', b2: '#07020d', rim: 'neon', sc: 'city', p: 'neon', f: 'Orbitron', t: ['NEON', 'NIGHTS 777'] },
    { w: ['Neon 7', '7', '#ff2bd6'], s: ['Star', '⭐', '#ffeb3b'],
      h: [['Slot Machine', '🎰', '#e91e63'], ['Joker', '🃏', '#7c4dff'], ['Dice', '🎲', '#eceff1'], ['Cocktail', '🍸', '#18e0ff']],
      l: [['Kiss', '💋', '#ff1744'], ['Music', '🎵', '#40c4ff'], ['Cherry', '🍒', '#e3212b'], ['Lemon', '🍋', '#f5d400']] }),
  sk('vegas_fruits', 'liberty_bells', 'Liberty Bells', 'classic',
    { a: '#ffd23f', b1: '#0d3b2a', b2: '#021009', rim: 'gold', sc: 'marquee', p: 'lights', f: 'Bungee', light: true },
    { w: ['Gold 7', '7', '#d4a017'], s: ['Star', '⭐', '#ffc933'],
      h: [['BAR', 'BAR', '#222'], ['Liberty Bell', '🔔', '#f0a500'], ['Clover', '🍀', '#43a047'], ['Top Hat', '🎩', '#37474f']],
      l: [['Coin', '🪙', '#ffd23f'], ['Plum', '🫐', '#5b5fc7'], ['Orange', '🍊', '#ff8c1a'], ['Cherry', '🍒', '#e3212b']] }),
  sk('vegas_fruits', 'frozen_fruits', 'Frozen Fruit Ice', 'classic',
    { a: '#80deea', b1: '#0e3a57', b2: '#020b14', rim: 'ice', sc: 'snow', p: 'snow', f: 'Bungee', light: true, t: ['FROZEN', 'FRUIT ICE'] },
    { w: ['Ice 7', '7', '#00acc1'], s: ['Snowflake', '❄️', '#81d4fa'],
      h: [['Shaved Ice', '🍧', '#f48fb1'], ['Ice Cream', '🍦', '#ffe0b2'], ['Strawberry', '🍓', '#e53935'], ['Blueberry', '🫐', '#5c6bc0']],
      l: [['Grapes', '🍇', '#8e44ad'], ['Watermelon', '🍉', '#3cb44b'], ['Lemon', '🍋', '#f5d400'], ['Cherry', '🍒', '#e3212b']] }),
  sk('vegas_fruits', 'tropical_punch', 'Tropical Punch 7s', 'classic',
    { a: '#ff9100', b1: '#6b1d4a', b2: '#170311', rim: 'rose', sc: 'sunburst', p: 'sparkle', f: 'Bungee', light: true, t: ['TROPICAL', 'PUNCH 7s'] },
    { w: ['Mango 7', '7', '#ff6d00'], s: ['Hibiscus', '🌺', '#ff4081'],
      h: [['Pineapple', '🍍', '#ffca28'], ['Coconut', '🥥', '#8d6e63'], ['Mango', '🥭', '#ff9800'], ['Banana', '🍌', '#ffee58']],
      l: [['Watermelon', '🍉', '#3cb44b'], ['Orange', '🍊', '#ff8c1a'], ['Lemon', '🍋', '#f5d400'], ['Cherry', '🍒', '#e3212b']] }),
  sk('vegas_fruits', 'royal_crown_7s', 'Royal Crown 7s', 'classic',
    { a: '#d6a8ff', b1: '#351050', b2: '#0b0312', rim: 'amethyst', sc: 'marquee', p: 'lights', f: 'Cinzel', light: true, t: ['ROYAL', 'CROWN 7s'] },
    { w: ['Royal 7', '7', '#8e24aa'], s: ['Star', '⭐', '#ffc933'],
      h: [['Crown', '👑', '#ffc233'], ['Diamond', '💎', '#4fc3f7'], ['BAR', 'BAR', '#222'], ['Bell', '🔔', '#f0a500']],
      l: [['Grapes', '🍇', '#8e44ad'], ['Peach', '🍑', '#ff9a5a'], ['Orange', '🍊', '#ff8c1a'], ['Cherry', '🍒', '#e3212b']] }),
  sk('vegas_fruits', 'farmers_market', "Farmer's Market", 'classic',
    { a: '#8bc34a', b1: '#33691e', b2: '#0a1a04', rim: 'wood', sc: 'hills', p: 'leaves', f: 'Bungee', light: true, t: ["FARMER'S", 'MARKET'] },
    { w: ['Farmer Wild', '🧑‍🌾', '#8bc34a'], s: ['Sunflower', '🌻', '#ffc107'],
      h: [['Carrot', '🥕', '#ff7043'], ['Red Apple', '🍎', '#e53935'], ['Pear', '🍐', '#c0ca33'], ['Corn', '🌽', '#ffd23f']],
      l: [['Tomato', '🍅', '#e53935'], ['Potato', '🥔', '#a1887f'], ['Cucumber', '🥒', '#66bb6a'], ['Eggplant', '🍆', '#7b1fa2']] }),
  sk('vegas_fruits', 'berry_blast', 'Berry Blast', 'classic',
    { a: '#e040fb', b1: '#4a0f4a', b2: '#110311', rim: 'rose', sc: 'bubbles', p: 'sparkle', f: 'Fredoka', light: true },
    { w: ['Berry 7', '7', '#ad1457'], s: ['Star', '⭐', '#ffc933'],
      h: [['Strawberry', '🍓', '#e53935'], ['Blueberry', '🫐', '#5c6bc0'], ['Grapes', '🍇', '#8e44ad'], ['Cherries', '🍒', '#e3212b']],
      l: [['Peach', '🍑', '#ff9a5a'], ['Melon', '🍈', '#aed581'], ['Kiwi', '🥝', '#7cb342'], ['Lemon', '🍋', '#f5d400']] }),
  sk('vegas_fruits', 'arcade_8bit', 'Arcade 8-Bit', 'classic',
    { a: '#76ff03', b1: '#0a1a3a', b2: '#01030a', rim: 'neon', sc: 'neongrid', p: 'neon', f: 'Russo One', t: ['ARCADE', '8-BIT'] },
    { w: ['Pixel 7', '7', '#76ff03'], s: ['Invader', '👾', '#e040fb'],
      h: [['Joystick', '🕹️', '#ff1744'], ['Gamepad', '🎮', '#90a4ae'], ['Mushroom', '🍄', '#e53935'], ['Ghost', '👻', '#eceff1']],
      l: [['BAR', 'BAR', '#222'], ['Bell', '🔔', '#f0a500'], ['Strawberry', '🍓', '#e53935'], ['Cherry', '🍒', '#e3212b']] }),
  sk('vegas_fruits', 'vintage_club', 'Vintage Club', 'classic',
    { a: '#ffd54f', b1: '#0b3d24', b2: '#02100a', rim: 'gold', sc: 'marquee', p: 'dust', f: 'Lobster', light: true },
    { w: ['Club 7', '7', '#c62828'], s: ['Dice', '🎲', '#eceff1'],
      h: [['Joker', '🃏', '#7c4dff'], ['Spade', '♠️', '#212121'], ['Heart', '♥️', '#d32f2f'], ['Club', '♣️', '#212121']],
      l: [['Diamond', '♦️', '#d32f2f'], ['Martini', '🍸', '#26c6da'], ['BAR', 'BAR', '#222'], ['Cherry', '🍒', '#e3212b']] }),
  sk('vegas_fruits', 'candy_7s', 'Candy 7s', 'classic',
    { a: '#ff5fa2', b1: '#ff9ccf', b2: '#7b3fc4', rim: 'rose', sc: 'bubbles', p: 'sparkle', f: 'Fredoka', light: true },
    { w: ['Candy 7', '7', '#ec407a'], s: ['Lollipop', '🍭', '#ff5fa2'],
      h: [['Cake', '🍰', '#f8bbd0'], ['Cupcake', '🧁', '#ce93d8'], ['Donut', '🍩', '#ffab91'], ['Chocolate', '🍫', '#795548']],
      l: [['Candy', '🍬', '#ff80ab'], ['Cookie', '🍪', '#c98a4b'], ['Pudding', '🍮', '#ffcc80'], ['Cherry', '🍒', '#e3212b']] }),
  sk('vegas_fruits', 'cherry_bomb', 'Cherry Bomb 7s', 'classic',
    { a: '#ff1744', b1: '#1a1a1a', b2: '#000000', rim: 'ruby', sc: 'marquee', p: 'embers', f: 'Bangers', light: true, t: ['CHERRY', 'BOMB 7s'] },
    { w: ['Blazing 7', '7', '#ff1744'], s: ['Bomb', '💣', '#424242'],
      h: [['BAR', 'BAR', '#222'], ['Cherries', '🍒', '#e3212b'], ['Fire', '🔥', '#ff9100'], ['Bell', '🔔', '#f0a500']],
      l: [['Plum', '🫐', '#5b5fc7'], ['Orange', '🍊', '#ff8c1a'], ['Lemon', '🍋', '#f5d400'], ['Grapes', '🍇', '#8e44ad']] })
];

// ------------------------------------------------------------------ 243 ways 5x3 (cyber_neon)
const WAYS243 = [
  sk('cyber_neon', 'robo_factory', 'Robo Factory', 'scifi',
    { a: '#ffab40', b1: '#263238', b2: '#06090b', rim: 'silver', sc: 'city', p: 'embers', f: 'Russo One' },
    { w: ['Gear Wild', '⚙️', '#ffab40'], s: ['Power Surge', '⚡', '#ffeb3b'],
      h: [['Mech Arm', '🦾', '#90a4ae'], ['Wrench', '🔧', '#b0bec5'], ['Bolt', '🔩', '#78909c'], ['Bulb', '💡', '#ffee58']] }),
  sk('cyber_neon', 'synthwave_city', 'Synthwave City', 'scifi',
    { a: '#ff4ecd', b1: '#2b0b4a', b2: '#07020f', rim: 'neon', sc: 'neongrid', p: 'neon', f: 'Orbitron' },
    { w: ['Night City', '🌆', '#ff4ecd'], s: ['Sunset Drive', '🌇', '#ffab40'],
      h: [['Race Car', '🏎️', '#ff1744'], ['Headphones', '🎧', '#18e0ff'], ['Tape', '📼', '#b388ff'], ['Shades', '🕶️', '#eceff1']] }),
  sk('cyber_neon', 'alien_invasion', 'Alien Invasion', 'space',
    { a: '#76ff03', b1: '#0c2a1c', b2: '#010805', rim: 'emerald', sc: 'space', p: 'stars', f: 'Orbitron' },
    { w: ['Mothership', '🛸', '#76ff03'], s: ['Meteor', '☄️', '#ff8a65'],
      h: [['Alien', '👽', '#76ff03'], ['Tentacles', '🐙', '#e040fb'], ['DNA', '🧬', '#40c4ff'], ['Telescope', '🔭', '#b0bec5']] }),
  sk('cyber_neon', 'golden_tiger_ways', 'Golden Tiger Ways', 'asian',
    { a: '#ffc233', b1: '#6b0d12', b2: '#140204', rim: 'gold', sc: 'mountains', p: 'petals', f: 'Cinzel', med: true },
    { w: ['Tiger Wild', '🐅', '#ffc233'], s: ['Red Envelope', '🧧', '#e53935'],
      h: [['Tiger Head', '🐯', '#ffa726'], ['Lotus', '🪷', '#f48fb1'], ['Bamboo', '🎋', '#66bb6a'], ['Mahjong', '🀄', '#eceff1']] }),
  sk('cyber_neon', 'ninja_shadow', 'Ninja Shadow', 'asian',
    { a: '#b388ff', b1: '#1d1036', b2: '#05020b', rim: 'obsidian', sc: 'mountains', p: 'petals', f: 'Russo One' },
    { w: ['Ninja Wild', '🥷', '#b388ff'], s: ['Crescent', '🌙', '#fff59d'],
      h: [['Blade', '🗡️', '#cfd8dc'], ['Castle', '🏯', '#ffb74d'], ['Sakura', '🌸', '#f48fb1'], ['Bamboo', '🎋', '#66bb6a']] }),
  sk('cyber_neon', 'inferno_ways', 'Inferno Ways', 'fantasy',
    { a: '#ff6d00', b1: '#4a0c02', b2: '#0e0200', rim: 'ruby', sc: 'volcano', p: 'embers', f: 'Bangers' },
    { w: ['Flame Wild', '🔥', '#ff6d00'], s: ['Volcano', '🌋', '#ff3d00'],
      h: [['Ogre', '👹', '#e53935'], ['Imp', '😈', '#7e57c2'], ['Dragon', '🐉', '#43a047'], ['Fireball', '☄️', '#ff8a65']] }),
  sk('cyber_neon', 'deep_sea_ways', 'Deep Sea Ways', 'ocean',
    { a: '#40c4ff', b1: '#032a4a', b2: '#000a14', rim: 'ice', sc: 'ocean', p: 'bubbles', f: 'Russo One', med: true },
    { w: ['Shark Wild', '🦈', '#40c4ff'], s: ['Trident', '🔱', '#ffd54f'],
      h: [['Octopus', '🐙', '#ec407a'], ['Pufferfish', '🐡', '#ffca28'], ['Squid', '🦑', '#ff8a65'], ['Reef Fish', '🐠', '#29b6f6']] }),
  sk('cyber_neon', 'howling_moon', 'Howling Moon', 'animals',
    { a: '#cfd8dc', b1: '#1a2340', b2: '#03050c', rim: 'silver', sc: 'forest', p: 'stars', f: 'Cinzel', med: true },
    { w: ['Wolf Wild', '🐺', '#cfd8dc'], s: ['Full Moon', '🌕', '#fff59d'],
      h: [['Owl', '🦉', '#a1887f'], ['Stag', '🦌', '#8d6e63'], ['Fox', '🦊', '#ff8a50'], ['Bear', '🐻', '#795548']] }),
  sk('cyber_neon', 'jurassic_ways', 'Jurassic Ways', 'adventure',
    { a: '#aeea00', b1: '#1f3d12', b2: '#050d02', rim: 'emerald', sc: 'jungle', p: 'leaves', f: 'Bangers', med: true },
    { w: ['T-Rex Wild', '🦖', '#aeea00'], s: ['Volcano', '🌋', '#ff5722'],
      h: [['Long Neck', '🦕', '#66bb6a'], ['Dino Egg', '🥚', '#ffe0b2'], ['Fossil', '🦴', '#eeeeee'], ['Fern', '🌿', '#43a047']] }),
  sk('cyber_neon', 'crypto_rush', 'Crypto Rush', 'scifi',
    { a: '#00e676', b1: '#062a1a', b2: '#000a05', rim: 'emerald', sc: 'neongrid', p: 'neon', f: 'Orbitron' },
    { w: ['To The Moon', '🚀', '#00e676'], s: ['Bull Chart', '💹', '#69f0ae'],
      h: [['Money Bag', '💰', '#ffc233'], ['Diamond Hands', '💎', '#4fc3f7'], ['Coin', '🪙', '#ffd23f'], ['Vault', '🏦', '#b0bec5']] }),
  sk('cyber_neon', 'thunder_stallions', 'Thunder Stallions', 'western',
    { a: '#ffcc80', b1: '#5a2e12', b2: '#140903', rim: 'bronze', sc: 'savanna', p: 'dust', f: 'Rye', med: true },
    { w: ['Stallion Wild', '🐎', '#ffcc80'], s: ['Twister', '🌪️', '#b0bec5'],
      h: [['Eagle', '🦅', '#8d6e63'], ['Bison', '🦬', '#6d4c41'], ['Bow', '🏹', '#a1887f'], ['Feather', '🪶', '#e0e0e0']] }),
  sk('cyber_neon', 'grand_circus', 'Grand Circus', 'fun',
    { a: '#ffeb3b', b1: '#8b0000', b2: '#1a0000', rim: 'gold', sc: 'sunburst', p: 'lights', f: 'Bangers', med: true },
    { w: ['Clown Wild', '🤡', '#ffeb3b'], s: ['Big Top', '🎪', '#e53935'],
      h: [['Elephant', '🐘', '#90a4ae'], ['Lion', '🦁', '#ffb300'], ['Top Hat', '🎩', '#37474f'], ['Ticket', '🎟️', '#ffca28']] }),
  sk('cyber_neon', 'monster_lab', 'Monster Lab', 'horror',
    { a: '#76ff03', b1: '#10221a', b2: '#020604', rim: 'obsidian', sc: 'graveyard', p: 'embers', f: 'Creepster', med: true },
    { w: ['Zombie Wild', '🧟', '#76ff03'], s: ['Potion', '🧪', '#40c4ff'],
      h: [['Brain', '🧠', '#f48fb1'], ['Eyeball', '👁️', '#90caf9'], ['Bones', '🦴', '#eeeeee'], ['Spider', '🕷️', '#9e9e9e']] })
];

// ------------------------------------------------------------------ tumble + accumulating multipliers (olympus_thunder)
const TUMBLE_ACC = [
  sk('olympus_thunder', 'temple_of_poseidon', 'Temple of Poseidon', 'mythology',
    { a: '#4dd0e1', b1: '#0b4a6e', b2: '#021320', rim: 'marble', sc: 'ocean', p: 'bubbles', f: 'Cinzel', t: ['TEMPLE OF', 'POSEIDON'] },
    { s: ['Trident Orb', '🔱', '#4dd0e1'], m: '🔱',
      h: [['Crown', '👑', '#ffd54f'], ['Conch', '🐚', '#ffccbc'], ['Dolphin', '🐬', '#4fc3f7'], ['Amphora', '🏺', '#d9774a']],
      gems: [['#00bcd4', 'heart'], ['#3f51b5', 'oval'], ['#26a69a', 'triangle'], ['#81d4fa', 'octagon'], ['#1e88e5', 'hex']] }),
  sk('olympus_thunder', 'underworld_flames', 'Underworld Flames', 'mythology',
    { a: '#ff5722', b1: '#3a0703', b2: '#0c0100', rim: 'ruby', sc: 'volcano', p: 'embers', f: 'Cinzel' },
    { s: ['Skull Orb', '💀', '#ff5722'], m: '🔥',
      h: [['Demon', '👹', '#e53935'], ['Old Key', '🗝️', '#ffb74d'], ['Hourglass', '⏳', '#ffa726'], ['Wine', '🍷', '#ad1457']],
      gems: [['#d50000', 'heart'], ['#6a1b9a', 'oval'], ['#ff6d00', 'triangle'], ['#2e7d32', 'octagon'], ['#37474f', 'hex']] }),
  sk('olympus_thunder', 'moon_goddess', 'Moon Goddess', 'fantasy',
    { a: '#f8bbd0', b1: '#2a1a5e', b2: '#07041a', rim: 'rose', sc: 'space', p: 'stars', f: 'Cinzel' },
    { s: ['Moon Orb', '🌙', '#fff59d'], m: '⭐',
      h: [['Princess', '👸', '#f8bbd0'], ['Unicorn', '🦄', '#e1bee7'], ['Stardust', '💫', '#fff176'], ['Crystal Ball', '🔮', '#b39ddb']],
      gems: [['#f06292', 'heart'], ['#ba68c8', 'oval'], ['#ffd54f', 'triangle'], ['#4db6ac', 'octagon'], ['#7986cb', 'hex']] }),
  sk('olympus_thunder', 'sun_god_ra', 'Sun God Ra', 'egypt',
    { a: '#ffc233', b1: '#6b3f06', b2: '#140a01', rim: 'gold', sc: 'dunes', p: 'dust', f: 'Cinzel' },
    { s: ['Sun Disc', '☀️', '#ffc233'], m: '👁️',
      h: [['Falcon', '🦅', '#e8a33d'], ['Cobra', '🐍', '#43c26b'], ['Scarab', '🪲', '#3fb7e0'], ['Canopic Jar', '🏺', '#d9774a']],
      gems: [['#e53935', 'heart'], ['#1e88e5', 'oval'], ['#ffb300', 'triangle'], ['#00897b', 'octagon'], ['#5e35b1', 'hex']] }),
  sk('olympus_thunder', 'jaguar_gold', 'Jaguar Gold', 'aztec',
    { a: '#ffd23f', b1: '#1b4d2a', b2: '#041008', rim: 'jade', sc: 'jungle', p: 'leaves', f: 'Bungee' },
    { s: ['Stone Idol', '🗿', '#9fb3a1'], m: '🌞',
      h: [['Jaguar', '🐆', '#f0a030'], ['Macaw', '🦜', '#e8483f'], ['Serpent', '🐍', '#2fbf71'], ['Maize', '🌽', '#ffd23f']],
      gems: [['#00c853', 'heart'], ['#d50000', 'diamond'], ['#ffab00', 'triangle'], ['#00b8d4', 'octagon'], ['#6200ea', 'hex']] }),
  sk('olympus_thunder', 'frost_giant', 'Frost Giant', 'winter',
    { a: '#b3e5fc', b1: '#16456b', b2: '#030c16', rim: 'ice', sc: 'snow', p: 'snow', f: 'Cinzel' },
    { s: ['Snowflake', '❄️', '#81d4fa'], m: '💠',
      h: [['Snowman', '⛄', '#eceff1'], ['Ice Cube', '🧊', '#b3e5fc'], ['Polar Bear', '🐻‍❄️', '#e1f5fe'], ['Reindeer', '🦌', '#a1887f']],
      gems: [['#e1f5fe', 'heart'], ['#81d4fa', 'oval'], ['#4fc3f7', 'triangle'], ['#b39ddb', 'octagon'], ['#90a4ae', 'hex']] }),
  sk('olympus_thunder', 'dragon_pearls', 'Dragon Pearls', 'asian',
    { a: '#3ddc97', b1: '#6b0d12', b2: '#140204', rim: 'jade', sc: 'mountains', p: 'petals', f: 'Cinzel' },
    { s: ['Dragon Orb', '🐉', '#3ddc97'], m: '☯️',
      h: [['Lantern', '🏮', '#ff4d3d'], ['Envelope', '🧧', '#e53935'], ['Lotus', '🪷', '#f48fb1'], ['Mahjong', '🀄', '#eceff1']],
      gems: [['#00c853', 'heart'], ['#ffd600', 'oval'], ['#ff6d00', 'triangle'], ['#26a69a', 'octagon'], ['#c62828', 'hex']] }),
  sk('olympus_thunder', 'cosmic_crystals', 'Cosmic Crystals', 'space',
    { a: '#b388ff', b1: '#170d3b', b2: '#02010a', rim: 'amethyst', sc: 'space', p: 'stars', f: 'Orbitron' },
    { s: ['Galaxy', '🌌', '#b388ff'], m: '🌟',
      h: [['Planet', '🪐', '#ffb74d'], ['Rocket', '🚀', '#eceff1'], ['Alien', '👽', '#76ff03'], ['Comet', '☄️', '#ff8a65']],
      gems: [['#ff4081', 'heart'], ['#7c4dff', 'oval'], ['#ffd740', 'triangle'], ['#64ffda', 'octagon'], ['#448aff', 'hex']] }),
  sk('olympus_thunder', 'dwarven_forge', 'Dwarven Forge', 'fantasy',
    { a: '#ff9100', b1: '#3a2415', b2: '#0c0603', rim: 'bronze', sc: 'volcano', p: 'embers', f: 'Cinzel' },
    { s: ['Hammer & Pick', '⚒️', '#b0bec5'], m: '🔥',
      h: [['Shield', '🛡️', '#8d6e63'], ['Axe', '🪓', '#90a4ae'], ['Crown', '👑', '#ffc233'], ['Ale', '🍺', '#ffb300']],
      gems: [['#e53935', 'heart'], ['#8e24aa', 'oval'], ['#ffb300', 'triangle'], ['#43a047', 'octagon'], ['#1e88e5', 'hex']] }),
  sk('olympus_thunder', 'fairy_garden', 'Fairy Garden', 'fantasy',
    { a: '#f48fb1', b1: '#2e6b3a', b2: '#0a1a0d', rim: 'rose', sc: 'forest', p: 'petals', f: 'Fredoka' },
    { s: ['Fairy', '🧚', '#f48fb1'], m: '🌸',
      h: [['Mushroom', '🍄', '#e53935'], ['Butterfly', '🦋', '#42a5f5'], ['Ladybug', '🐞', '#e53935'], ['Tulip', '🌷', '#f06292']],
      gems: [['#ff80ab', 'heart'], ['#ea80fc', 'oval'], ['#ffff8d', 'triangle'], ['#b9f6ca', 'octagon'], ['#80d8ff', 'hex']] }),
  sk('olympus_thunder', 'wizard_tower', "Wizard's Tower", 'fantasy',
    { a: '#b388ff', b1: '#24104a', b2: '#06020f', rim: 'amethyst', sc: 'castle', p: 'sparkle', f: 'Cinzel', t: ["WIZARD'S", 'TOWER'] },
    { s: ['Wizard', '🧙', '#b388ff'], m: '✨',
      h: [['Spellbook', '📖', '#8d6e63'], ['Owl', '🦉', '#a1887f'], ['Old Key', '🗝️', '#ffb74d'], ['Potion', '🧪', '#40c4ff']],
      gems: [['#e040fb', 'heart'], ['#651fff', 'oval'], ['#ffd740', 'triangle'], ['#1de9b6', 'octagon'], ['#2979ff', 'hex']] }),
  sk('olympus_thunder', 'carnival_gems', 'Carnival Gems', 'fun',
    { a: '#ffea00', b1: '#006064', b2: '#00181a', rim: 'gold', sc: 'sunburst', p: 'sparkle', f: 'Bangers' },
    { s: ['Masks', '🎭', '#ffea00'], m: '🎉',
      h: [['Dancer', '💃', '#e53935'], ['Drum', '🥁', '#ff7043'], ['Peacock', '🦚', '#26a69a'], ['Trumpet', '🎺', '#ffc233']],
      gems: [['#ff1744', 'heart'], ['#d500f9', 'oval'], ['#ffea00', 'triangle'], ['#00e676', 'octagon'], ['#2979ff', 'hex']] }),
  sk('olympus_thunder', 'valhalla_storm', 'Valhalla Storm', 'norse',
    { a: '#90caf9', b1: '#263a52', b2: '#060a12', rim: 'silver', sc: 'mountains', p: 'snow', f: 'Cinzel' },
    { s: ['Storm', '🌩️', '#90caf9'], m: '⚡',
      h: [['Shield', '🛡️', '#8d6e63'], ['War Axe', '🪓', '#90a4ae'], ['Wolf', '🐺', '#b0bec5'], ['Mead', '🍺', '#ffb300']],
      gems: [['#c62828', 'heart'], ['#4527a0', 'oval'], ['#f9a825', 'triangle'], ['#2e7d32', 'octagon'], ['#1565c0', 'hex']] }),
  sk('olympus_thunder', 'desert_djinn', 'Desert Djinn', 'arabian',
    { a: '#ffc233', b1: '#5a2a6e', b2: '#12051a', rim: 'gold', sc: 'dunes', p: 'sparkle', f: 'Cinzel' },
    { s: ['Genie', '🧞', '#4fc3f7'], m: '🪔',
      h: [['Camel', '🐪', '#d7a86e'], ['Ring', '💍', '#b0bec5'], ['Vase', '🏺', '#d9774a'], ['Scimitar', '🗡️', '#cfd8dc']],
      gems: [['#e53935', 'heart'], ['#8e24aa', 'oval'], ['#ffb300', 'triangle'], ['#00897b', 'octagon'], ['#1e88e5', 'hex']] })
];

// ------------------------------------------------------------------ tumble + bombs (sweet_sugar)
const TUMBLE_BOMB = [
  sk('sweet_sugar', 'juice_bar', 'Juice Bar Cascade', 'fruits',
    { a: '#ff9100', b1: '#ffb74d', b2: '#e64a19', rim: 'candy', sc: 'sunburst', p: 'sparkle', f: 'Fredoka', t: ['JUICE BAR', 'CASCADE'] },
    { s: ['Smoothie', '🥤', '#ff4081'], m: '🍹',
      h: [['Strawberry', '🍓', '#e53935'], ['Pineapple', '🍍', '#ffca28'], ['Mango', '🥭', '#ff9800'], ['Peach', '🍑', '#ff8a65']],
      l: [['Grapes', '🍇', '#8e44ad'], ['Watermelon', '🍉', '#3cb44b'], ['Orange', '🍊', '#ff8c1a'], ['Lemon', '🍋', '#f5d400'], ['Kiwi', '🥝', '#7cb342']] }),
  sk('sweet_sugar', 'donut_delight', 'Donut Delight', 'sweets',
    { a: '#ff80ab', b1: '#ffd1dc', b2: '#a0527a', rim: 'candy', sc: 'bubbles', p: 'sparkle', f: 'Fredoka' },
    { s: ['Coffee', '☕', '#8d6e63'], m: '🍬',
      h: [['Birthday Cake', '🎂', '#f48fb1'], ['Cake Slice', '🍰', '#fff3e0'], ['Cupcake', '🧁', '#ce93d8'], ['Donut', '🍩', '#ffab91']],
      l: [['Chocolate', '🍫', '#795548'], ['Cookie', '🍪', '#c98a4b'], ['Croissant', '🥐', '#ffb74d'], ['Pancakes', '🥞', '#ffcc80'], ['Waffle', '🧇', '#e0a060']] }),
  sk('sweet_sugar', 'gelato_cascade', 'Gelato Cascade', 'sweets',
    { a: '#80deea', b1: '#b2ebf2', b2: '#4f6fb3', rim: 'ice', sc: 'bubbles', p: 'snow', f: 'Fredoka' },
    { s: ['Ice Cube', '🧊', '#80deea'], m: '🍡',
      h: [['Sundae', '🍨', '#f8bbd0'], ['Cone', '🍦', '#ffe0b2'], ['Shaved Ice', '🍧', '#f48fb1'], ['Cherry', '🍒', '#e53935']],
      l: [['Strawberry', '🍓', '#e53935'], ['Blueberry', '🫐', '#5c6bc0'], ['Chocolate', '🍫', '#795548'], ['Coconut', '🥥', '#8d6e63'], ['Lemon', '🍋', '#f5d400']] }),
  sk('sweet_sugar', 'sushi_cascade', 'Sushi Cascade', 'asian',
    { a: '#ff5252', b1: '#263238', b2: '#07090b', rim: 'wood', sc: 'mountains', p: 'petals', f: 'Bangers' },
    { s: ['Carp Streamer', '🎏', '#ff5252'], m: '🧨',
      h: [['Sushi', '🍣', '#ff8a65'], ['Tempura', '🍤', '#ffb74d'], ['Onigiri', '🍙', '#eceff1'], ['Bento', '🍱', '#e53935']],
      l: [['Dumpling', '🥟', '#ffe0b2'], ['Ramen', '🍜', '#ffcc80'], ['Fish Cake', '🍥', '#f8bbd0'], ['Chopsticks', '🥢', '#a1887f'], ['Green Tea', '🍵', '#9ccc65']] }),
  sk('sweet_sugar', 'pet_parade', 'Pet Parade', 'animals',
    { a: '#ffca28', b1: '#81d4fa', b2: '#3949ab', rim: 'candy', sc: 'hills', p: 'sparkle', f: 'Fredoka' },
    { s: ['Pet House', '🏠', '#ff7043'], m: '🎾',
      h: [['Puppy', '🐶', '#d7a86e'], ['Kitten', '🐱', '#ffb74d'], ['Bunny', '🐰', '#eceff1'], ['Hamster', '🐹', '#ffcc80']],
      l: [['Parrot', '🦜', '#e53935'], ['Goldfish', '🐠', '#29b6f6'], ['Turtle', '🐢', '#66bb6a'], ['Bone', '🦴', '#eeeeee'], ['Yarn', '🧶', '#f06292']] }),
  sk('sweet_sugar', 'blooming_garden', 'Blooming Garden', 'nature',
    { a: '#ff4081', b1: '#a5d6a7', b2: '#2e7d32', rim: 'rose', sc: 'hills', p: 'petals', f: 'Fredoka' },
    { s: ['Honey Bee', '🐝', '#ffca28'], m: '🦋',
      h: [['Rose', '🌹', '#e53935'], ['Tulip', '🌷', '#f06292'], ['Sunflower', '🌻', '#ffc107'], ['Daisy', '🌼', '#fff176']],
      l: [['Blossom', '🌸', '#f48fb1'], ['Hyacinth', '🪻', '#9575cd'], ['Clover', '🍀', '#43a047'], ['Herb', '🌿', '#66bb6a'], ['Mushroom', '🍄', '#e53935']] }),
  sk('sweet_sugar', 'christmas_cascade', 'Christmas Cascade', 'holiday',
    { a: '#ff5252', b1: '#1b5e20', b2: '#06180a', rim: 'ruby', sc: 'snow', p: 'snow', f: 'Lobster' },
    { s: ['Gift', '🎁', '#e53935'], m: '🎀',
      h: [['Santa', '🎅', '#e53935'], ['Tree', '🎄', '#43a047'], ['Snowman', '⛄', '#eceff1'], ['Reindeer', '🦌', '#a1887f']],
      l: [['Bell', '🔔', '#ffc233'], ['Gingerbread', '🍪', '#c98a4b'], ['Stocking', '🧦', '#e53935'], ['Candle', '🕯️', '#ffcc80'], ['Star', '⭐', '#ffd54f']] }),
  sk('sweet_sugar', 'trick_or_treat', 'Trick or Treat', 'holiday',
    { a: '#ff9800', b1: '#3a1a52', b2: '#0a0412', rim: 'obsidian', sc: 'graveyard', p: 'embers', f: 'Creepster' },
    { s: ['Witch', '🧙‍♀️', '#9ccc65'], m: '🧪',
      h: [['Pumpkin', '🎃', '#ff9800'], ['Ghost', '👻', '#eceff1'], ['Bat', '🦇', '#7e57c2'], ['Spider', '🕷️', '#9e9e9e']],
      l: [['Candy', '🍬', '#ff80ab'], ['Lollipop', '🍭', '#ff5fa2'], ['Chocolate', '🍫', '#795548'], ['Web', '🕸️', '#cfd8dc'], ['Moon', '🌙', '#fff59d']] }),
  sk('sweet_sugar', 'crystal_cavern', 'Crystal Cavern', 'gems',
    { a: '#18ffff', b1: '#1a2a4a', b2: '#03060e', rim: 'amethyst', sc: 'volcano', p: 'sparkle', f: 'Orbitron' },
    { s: ['Crystal Ball', '🔮', '#b388ff'], m: '💣',
      h: [['Diamond', '💎', '#4fc3f7'], ['Ruby', null, '#ff1744', { gem: true, shape: 'heart' }], ['Emerald', null, '#00e676', { gem: true, shape: 'octagon' }], ['Sapphire', null, '#2979ff', { gem: true, shape: 'hex' }]],
      l: [['Amethyst', null, '#d500f9', { gem: true, shape: 'oval' }], ['Topaz', null, '#ffab00', { gem: true, shape: 'triangle' }], ['Aquamarine', null, '#18ffff', { gem: true, shape: 'diamond' }], ['Rose Quartz', null, '#ff80ab', { gem: true, shape: 'square' }], ['Citrine', null, '#ffea00', { gem: true, shape: 'hex' }]] }),
  sk('sweet_sugar', 'galactic_gummies', 'Galactic Gummies', 'space',
    { a: '#e040fb', b1: '#311b92', b2: '#07031a', rim: 'neon', sc: 'space', p: 'stars', f: 'Fredoka' },
    { s: ['Galaxy', '🌌', '#b388ff'], m: '💫',
      h: [['Ringed Planet', '🪐', '#ffb74d'], ['Earth', '🌍', '#42a5f5'], ['Moon', '🌙', '#fff59d'], ['Star', '⭐', '#ffd54f']],
      l: [['Comet', '☄️', '#ff8a65'], ['UFO', '🛸', '#b0bec5'], ['Invader', '👾', '#e040fb'], ['Rocket', '🚀', '#eceff1'], ['Shooting Star', '🌠', '#80d8ff']] }),
  sk('sweet_sugar', 'beach_party', 'Beach Party', 'ocean',
    { a: '#ffeb3b', b1: '#4fc3f7', b2: '#01579b', rim: 'candy', sc: 'ocean', p: 'bubbles', f: 'Bangers' },
    { s: ['Palm Tree', '🌴', '#66bb6a'], m: '☀️',
      h: [['Surfer', '🏄', '#29b6f6'], ['Dolphin', '🐬', '#4fc3f7'], ['Crab', '🦀', '#ff7043'], ['Shell', '🐚', '#ffccbc']],
      l: [['Cocktail', '🍹', '#ff8a65'], ['Shades', '🕶️', '#37474f'], ['Flip Flop', '🩴', '#ff4081'], ['Volleyball', '🏐', '#eceff1'], ['Watermelon', '🍉', '#3cb44b']] }),
  sk('sweet_sugar', 'honey_harvest', 'Honey Harvest', 'nature',
    { a: '#ffb300', b1: '#fff176', b2: '#e65100', rim: 'wood', sc: 'hills', p: 'sparkle', f: 'Fredoka' },
    { s: ['Honey Bee', '🐝', '#ffca28'], m: '🌼',
      h: [['Honey Pot', '🍯', '#ffb300'], ['Bear Cub', '🐻', '#8d6e63'], ['Sunflower', '🌻', '#ffc107'], ['Apple', '🍎', '#e53935']],
      l: [['Pear', '🍐', '#c0ca33'], ['Carrot', '🥕', '#ff7043'], ['Corn', '🌽', '#ffd23f'], ['Basket', '🧺', '#a1887f'], ['Mushroom', '🍄', '#e53935']] }),
  sk('sweet_sugar', 'tea_party', 'Tea Party', 'sweets',
    { a: '#ce93d8', b1: '#f3e5f5', b2: '#7b1fa2', rim: 'rose', sc: 'bubbles', p: 'petals', f: 'Lobster' },
    { s: ['Top Hat', '🎩', '#6a1b9a'], m: '🍬',
      h: [['Teapot', '🫖', '#80cbc4'], ['Coffee', '☕', '#8d6e63'], ['Cake', '🍰', '#fff3e0'], ['Cupcake', '🧁', '#ce93d8']],
      l: [['Strawberry', '🍓', '#e53935'], ['Lemon', '🍋', '#f5d400'], ['Cookie', '🍪', '#c98a4b'], ['Croissant', '🥐', '#ffb74d'], ['Green Tea', '🍵', '#9ccc65']] }),
  sk('sweet_sugar', 'koi_pond', 'Lucky Koi Pond', 'asian',
    { a: '#ff7043', b1: '#4db6ac', b2: '#004d40', rim: 'jade', sc: 'ocean', p: 'bubbles', f: 'Fredoka', t: ['LUCKY', 'KOI POND'] },
    { s: ['Wind Chime', '🎐', '#80deea'], m: '🫧',
      h: [['Koi', '🐟', '#ff7043'], ['Tropical Fish', '🐠', '#29b6f6'], ['Blowfish', '🐡', '#ffca28'], ['Lotus', '🪷', '#f48fb1']],
      l: [['Frog', '🐸', '#66bb6a'], ['Duck', '🦆', '#8d6e63'], ['Turtle', '🐢', '#43a047'], ['Herb', '🌿', '#66bb6a'], ['Shell', '🐚', '#ffccbc']] })
];

// ------------------------------------------------------------------ 1024 ways 5x4 (jade_dragon)
const WAYS1024 = [
  sk('jade_dragon', 'bamboo_panda', 'Bamboo Panda', 'asian',
    { a: '#8bc34a', b1: '#1f4d1f', b2: '#051105', rim: 'jade', sc: 'mountains', p: 'leaves', f: 'Cinzel', med: true },
    { w: ['Panda Wild', '🐼', '#eceff1'], s: ['Bamboo', '🎋', '#66bb6a'],
      h: [['Lantern', '🏮', '#ff4d3d'], ['Dumplings', '🥟', '#ffe0b2'], ['Green Tea', '🍵', '#9ccc65'], ['Fan', '🪭', '#ff5fa2']] }),
  sk('jade_dragon', 'lion_dance', 'Lion Dance', 'asian',
    { a: '#ffc233', b1: '#8b0000', b2: '#1a0000', rim: 'gold', sc: 'sunburst', p: 'embers', f: 'Cinzel', med: true },
    { w: ['Lion Wild', '🦁', '#ffc233'], s: ['Red Envelope', '🧧', '#e53935'],
      h: [['Drum', '🥁', '#ff7043'], ['Lantern', '🏮', '#ff4d3d'], ['Gold Coin', '🪙', '#ffd23f'], ['Fireworks', '🎆', '#7c4dff']] }),
  sk('jade_dragon', 'geisha_garden', 'Geisha Garden', 'asian',
    { a: '#f48fb1', b1: '#4a1030', b2: '#12030b', rim: 'rose', sc: 'mountains', p: 'petals', f: 'Cinzel', med: true },
    { w: ['Kimono Wild', '👘', '#f48fb1'], s: ['Torii Gate', '⛩️', '#ff7043'],
      h: [['Fan', '🪭', '#ff5fa2'], ['Dolls', '🎎', '#e53935'], ['Dango', '🍡', '#f8bbd0'], ['Pagoda', '🏯', '#ffb74d']] }),
  sk('jade_dragon', 'eagle_canyon', 'Eagle Canyon', 'western',
    { a: '#ffab40', b1: '#8a3b12', b2: '#1c0a03', rim: 'bronze', sc: 'dunes', p: 'dust', f: 'Rye', med: true },
    { w: ['Eagle Wild', '🦅', '#ffab40'], s: ['Canyon', '🏜️', '#ff7043'],
      h: [['Bison', '🦬', '#6d4c41'], ['Coyote', '🐺', '#bcaaa4'], ['Rattler', '🐍', '#9ccc65'], ['Cactus', '🌵', '#43a047']] }),
  sk('jade_dragon', 'amazon_wild', 'Amazon Wild', 'jungle',
    { a: '#76ff03', b1: '#0f4020', b2: '#020d05', rim: 'emerald', sc: 'jungle', p: 'leaves', f: 'Bungee', med: true },
    { w: ['Panther Wild', '🐆', '#ffca28'], s: ['Hibiscus', '🌺', '#ff4081'],
      h: [['Crocodile', '🐊', '#558b2f'], ['Macaw', '🦜', '#e53935'], ['Monkey', '🐒', '#8d6e63'], ['Tree Frog', '🐸', '#66bb6a']] }),
  sk('jade_dragon', 'maneki_fortune', 'Maneki Fortune', 'lucky',
    { a: '#ffd23f', b1: '#a31515', b2: '#200303', rim: 'gold', sc: 'sunburst', p: 'sparkle', f: 'Cinzel', med: true },
    { w: ['Lucky Cat', '🐈', '#ffd23f'], s: ['Red Envelope', '🧧', '#e53935'],
      h: [['Gold Coin', '🪙', '#ffd23f'], ['Koi Streamer', '🎏', '#ff5252'], ['Rice Ball', '🍙', '#eceff1'], ['Flower Cards', '🎴', '#e53935']] }),
  sk('jade_dragon', 'ocean_kingdom', 'Ocean Kingdom', 'ocean',
    { a: '#40c4ff', b1: '#01426a', b2: '#00101c', rim: 'ice', sc: 'ocean', p: 'bubbles', f: 'Cinzel', med: true },
    { w: ['Whale Wild', '🐋', '#40c4ff'], s: ['Trident', '🔱', '#ffd54f'],
      h: [['Shark', '🦈', '#90a4ae'], ['Octopus', '🐙', '#ec407a'], ['Turtle', '🐢', '#66bb6a'], ['Lobster', '🦞', '#e53935']] }),
  sk('jade_dragon', 'prairie_thunder', 'Prairie Thunder', 'animals',
    { a: '#ffcc80', b1: '#6b3a12', b2: '#170a03', rim: 'bronze', sc: 'savanna', p: 'dust', f: 'Rye', med: true },
    { w: ['Bison Wild', '🦬', '#ffcc80'], s: ['Sunrise', '🌄', '#ff9100'],
      h: [['Horse', '🐎', '#8d6e63'], ['Eagle', '🦅', '#a1887f'], ['Wolf', '🐺', '#b0bec5'], ['Elk', '🦌', '#a1887f']] }),
  sk('jade_dragon', 'desert_empress', 'Desert Empress', 'egypt',
    { a: '#ffd54f', b1: '#0d3b5a', b2: '#020c14', rim: 'gold', sc: 'pyramids', p: 'dust', f: 'Cinzel', med: true },
    { w: ['Empress Wild', '👸', '#ffd54f'], s: ['Camel', '🐫', '#d7a86e'],
      h: [['Black Cat', '🐈‍⬛', '#7e57c2'], ['Scarab', '🪲', '#26c6da'], ['Vase', '🏺', '#d9774a'], ['Cobra', '🐍', '#66bb6a']] }),
  sk('jade_dragon', 'temple_monkey', 'Temple Monkey', 'asian',
    { a: '#ffab40', b1: '#5a3a10', b2: '#140c02', rim: 'jade', sc: 'jungle', p: 'leaves', f: 'Bungee', med: true },
    { w: ['Monkey King', '🐒', '#ffab40'], s: ['Golden Peach', '🍑', '#ff8a65'],
      h: [['Pagoda', '🏯', '#ffb74d'], ['Lotus', '🪷', '#f48fb1'], ['Banana', '🍌', '#ffee58'], ['Drum', '🥁', '#ff7043']] }),
  sk('jade_dragon', 'grizzly_ridge', 'Grizzly Ridge', 'animals',
    { a: '#bcaaa4', b1: '#1f3a2a', b2: '#040b07', rim: 'wood', sc: 'forest', p: 'leaves', f: 'Rye', med: true },
    { w: ['Grizzly Wild', '🐻', '#bcaaa4'], s: ['Pine Tree', '🌲', '#43a047'],
      h: [['Salmon', '🐟', '#ff8a65'], ['Deer', '🦌', '#a1887f'], ['Beaver', '🦫', '#8d6e63'], ['Honey', '🍯', '#ffb300']] }),
  sk('jade_dragon', 'snake_charmer', 'Snake Charmer', 'arabian',
    { a: '#ffc233', b1: '#5a0f3a', b2: '#12020c', rim: 'gold', sc: 'dunes', p: 'sparkle', f: 'Cinzel', med: true },
    { w: ['Cobra Wild', '🐍', '#66bb6a'], s: ['Flute', '🪈', '#d7a86e'],
      h: [['Elephant', '🐘', '#90a4ae'], ['Tiger', '🐅', '#ffa726'], ['Ring', '💍', '#b0bec5'], ['Oil Lamp', '🪔', '#ffb300']] })
];

// ------------------------------------------------------------------ 25 lines 5x4 (wild_safari)
const LINES25 = [
  sk('wild_safari', 'knights_quest', "Knight's Quest", 'fantasy',
    { a: '#ffd54f', b1: '#1a2a52', b2: '#040810', rim: 'silver', sc: 'castle', p: 'dust', f: 'Cinzel', med: true, t: ["KNIGHT'S", 'QUEST'] },
    { w: ['Castle Wild', '🏰', '#ffd54f'], s: ['Dragon', '🐉', '#43a047'],
      h: [['Sword', '🗡️', '#cfd8dc'], ['Shield', '🛡️', '#8d6e63'], ['Crown', '👑', '#ffc233'], ['Steed', '🐴', '#a1887f']] }),
  sk('wild_safari', 'outback_heat', 'Outback Heat', 'animals',
    { a: '#ff7043', b1: '#8a2f0a', b2: '#1c0702', rim: 'bronze', sc: 'dunes', p: 'dust', f: 'Bungee', med: true },
    { w: ['Kangaroo Wild', '🦘', '#ff7043'], s: ['Boomerang', '🪃', '#d7a86e'],
      h: [['Koala', '🐨', '#90a4ae'], ['Croc', '🐊', '#558b2f'], ['Lizard', '🦎', '#9ccc65'], ['Snake', '🐍', '#66bb6a']] }),
  sk('wild_safari', 'racing_legends', 'Racing Legends', 'sport',
    { a: '#ff1744', b1: '#1a1a24', b2: '#030306', rim: 'silver', sc: 'city', p: 'neon', f: 'Russo One', med: true },
    { w: ['Checkered Flag', '🏁', '#eceff1'], s: ['Trophy', '🏆', '#ffc233'],
      h: [['Race Car', '🏎️', '#ff1744'], ['Motorbike', '🏍️', '#90a4ae'], ['Wheel', '🛞', '#607d8b'], ['Fuel', '⛽', '#e53935']] }),
  sk('wild_safari', 'goal_rush', 'Goal Rush', 'sport',
    { a: '#00e676', b1: '#1b5e20', b2: '#041205', rim: 'emerald', sc: 'hills', p: 'lights', f: 'Russo One', med: true },
    { w: ['Ball Wild', '⚽', '#eceff1'], s: ['Cup', '🏆', '#ffc233'],
      h: [['Goal Net', '🥅', '#eceff1'], ['Boots', '👟', '#42a5f5'], ['Gloves', '🧤', '#66bb6a'], ['Jersey', '🎽', '#e53935']] }),
  sk('wild_safari', 'rock_legend', 'Rock Legend', 'music',
    { a: '#ff4081', b1: '#26063a', b2: '#06010d', rim: 'neon', sc: 'city', p: 'neon', f: 'Bangers', med: true },
    { w: ['Guitar Wild', '🎸', '#ff4081'], s: ['Microphone', '🎤', '#b0bec5'],
      h: [['Drums', '🥁', '#ff7043'], ['Keyboard', '🎹', '#eceff1'], ['Headphones', '🎧', '#18e0ff'], ['Record', '💿', '#b0bec5']] }),
  sk('wild_safari', 'sunken_galleon', 'Sunken Galleon', 'pirates',
    { a: '#ffd54f', b1: '#063a4a', b2: '#000d12', rim: 'bronze', sc: 'ocean', p: 'bubbles', f: 'Pirata One', med: true },
    { w: ['Anchor Wild', '⚓', '#ffd54f'], s: ['Compass', '🧭', '#ffca28'],
      h: [['Galleon', '🚢', '#8d6e63'], ['Kraken', '🦑', '#ec407a'], ['Loot', '💰', '#ffc233'], ['Doubloon', '🪙', '#ffd23f']] }),
  sk('wild_safari', 'tiki_paradise', 'Tiki Paradise', 'tropical',
    { a: '#ffab40', b1: '#00695c', b2: '#001a16', rim: 'wood', sc: 'sunburst', p: 'leaves', f: 'Bungee', med: true },
    { w: ['Tiki Wild', '🗿', '#bcaaa4'], s: ['Volcano', '🌋', '#ff5722'],
      h: [['Hibiscus', '🌺', '#ff4081'], ['Pineapple', '🍍', '#ffca28'], ['Coconut', '🥥', '#8d6e63'], ['Turtle', '🐢', '#66bb6a']] }),
  sk('wild_safari', 'derby_day', 'Derby Day', 'sport',
    { a: '#ffd54f', b1: '#1b4d2a', b2: '#041008', rim: 'gold', sc: 'hills', p: 'dust', f: 'Lobster', med: true },
    { w: ['Jockey Wild', '🏇', '#ffd54f'], s: ['Trophy', '🏆', '#ffc233'],
      h: [['Racehorse', '🐎', '#8d6e63'], ['Top Hat', '🎩', '#37474f'], ['Champagne', '🥂', '#fff59d'], ['Rose', '🌹', '#e53935']] }),
  sk('wild_safari', 'happy_farm', 'Happy Farm', 'animals',
    { a: '#ffeb3b', b1: '#7cb342', b2: '#1b3a0a', rim: 'wood', sc: 'hills', p: 'leaves', f: 'Fredoka', med: true },
    { w: ['Cow Wild', '🐄', '#eceff1'], s: ['Tractor', '🚜', '#e53935'],
      h: [['Pig', '🐖', '#f8bbd0'], ['Sheep', '🐑', '#eeeeee'], ['Rooster', '🐓', '#ff7043'], ['Egg', '🥚', '#ffe0b2']] }),
  sk('wild_safari', 'heist_night', 'Heist Night', 'crime',
    { a: '#00e5ff', b1: '#0a1a2a', b2: '#010307', rim: 'obsidian', sc: 'city', p: 'neon', f: 'Russo One', med: true },
    { w: ['Mastermind', '🦹', '#7c4dff'], s: ['Vault Lock', '🔐', '#ffc233'],
      h: [['Cash Bag', '💰', '#ffc233'], ['Diamond', '💎', '#4fc3f7'], ['Getaway Car', '🚗', '#e53935'], ['Banknotes', '💵', '#66bb6a']] }),
  sk('wild_safari', 'beer_fest', 'Beer Fest', 'fun',
    { a: '#ffc107', b1: '#1565c0', b2: '#051a3a', rim: 'wood', sc: 'hills', p: 'sparkle', f: 'Lobster', med: true },
    { w: ['Beer Wild', '🍺', '#ffc107'], s: ['Pretzel', '🥨', '#c98a4b'],
      h: [['Sausage', '🌭', '#e57373'], ['Cheese', '🧀', '#ffd54f'], ['Trumpet', '🎺', '#ffc233'], ['Accordion', '🪗', '#e53935']] }),
  sk('wild_safari', 'northern_lights', 'Northern Lights', 'winter',
    { a: '#69f0ae', b1: '#0b2a4a', b2: '#010610', rim: 'ice', sc: 'snow', p: 'stars', f: 'Cinzel', med: true },
    { w: ['Reindeer Wild', '🦌', '#69f0ae'], s: ['Aurora', '🌌', '#b388ff'],
      h: [['Wolf', '🐺', '#b0bec5'], ['Snowy Owl', '🦉', '#eceff1'], ['Polar Bear', '🐻‍❄️', '#e1f5fe'], ['Arctic Fox', '🦊', '#ff8a50']] })
];

const SKINS = [...LINES20, ...CLASSIC, ...WAYS243, ...TUMBLE_ACC, ...TUMBLE_BOMB, ...WAYS1024, ...LINES25];

module.exports = { SKINS };
