#!/usr/bin/env python3
"""
Cuts the pictures generated by scripts/gen-ai-art.js (art-src/<id>/) into game assets
(public/games/<id>/assets/) and writes stage.json — the game then appears in the catalog.

  python3 scripts/import-ai-art.py <id> [<id> ...]
  python3 scripts/import-ai-art.py --all          # every skin whose pictures are complete

Needs Pillow, numpy and scipy (pip3 install pillow numpy scipy).
"""
import importlib.util
import json
import os
import sys

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..')
spec = importlib.util.spec_from_file_location('import_art', os.path.join(ROOT, 'scripts', 'import-art.py'))
ia = importlib.util.module_from_spec(spec)
spec.loader.exec_module(ia)


def asset_name(kind, sid):
    if kind == 'titans' and sid == 'WILD':
        return 'wild_icon'
    if kind == 'titans' and sid == 'SHARK':
        return 'shark_icon'
    if sid.startswith('_'):
        return sid
    return 'sym_' + sid.lower()


def import_game(gid):
    src = os.path.join(ROOT, 'art-src', gid)
    brief = json.load(open(os.path.join(src, 'brief.json')))
    missing = [p['file'] for p in brief['pieces'] if not os.path.exists(os.path.join(src, p['file']))]
    if missing:
        print(f'- {gid}: missing {", ".join(missing)}, skipped')
        return False
    out = os.path.join(ROOT, 'public', 'games', gid, 'assets')
    os.makedirs(out, exist_ok=True)
    print(f'{gid}:')
    stage = None
    for p in brief['pieces']:
        f = os.path.join(src, p['file'])
        if p['role'] == 'stage':
            stage = ia.cmd_stage(f, out, brief.get('windows'), panel=not brief.get('windows'), reels=brief.get('reels'))
            from PIL import Image
            ia.write_cover(Image.open(os.path.join(out, 'stage.jpg')), out)
        elif p['role'] == 'sheet':
            boxes_file = os.path.join(src, 'boxes.json')
            boxes = json.load(open(boxes_file)).get(p['file'].rsplit('.', 1)[0] if p['file'] != 'symbols.png' else 'symbols') if os.path.exists(boxes_file) else None
            if p.get('grid'):  # hand-made sheet on an even grid [cols, rows]
                g = p['grid']
                ia.cmd_grid(f, out, [asset_name(brief['kind'], sid) for sid in p['ids']], g[0], g[1], holes=p.get('holes', True))
            elif boxes:  # hand-picked boxes (the generator did not keep the grid)
                ia.cmd_boxes(f, out, {asset_name(brief['kind'], sid): b for sid, b in boxes.items()})
            else:
                ia.cmd_sheet(f, out, [asset_name(brief['kind'], sid) for sid in p['ids']])
        elif p['role'] == 'symbol':
            rgba = ia.transparent(f)
            if rgba is None:
                rgba = ia.cut_out(ia.Image.open(f).convert('RGB'), (255, 255, 255), 28, holes=True)
            ia.fit_square(rgba).save(os.path.join(out, asset_name(brief['kind'], p['id']) + '.png'))
            print('  ✓', asset_name(brief['kind'], p['id']))
        elif p['role'] == 'strip':
            ia.cmd_strip(f, os.path.join(out, 'wild.png'))
        elif p['role'] == 'card':
            ia.cmd_card(f, out, ['giant'])
    # stage.json last: its presence puts the game into the catalog
    stage['image'] = f'/games/{gid}/assets/stage.jpg'
    json.dump(stage, open(os.path.join(out, 'stage.json'), 'w'), indent=1)
    print('  ✓ stage.json')
    return True


def main():
    args = sys.argv[1:]
    if not args:
        print(__doc__)
        sys.exit(1)
    ids = args
    if '--all' in args:
        ids = sorted(d for d in os.listdir(os.path.join(ROOT, 'art-src')) if os.path.exists(os.path.join(ROOT, 'art-src', d, 'brief.json')))
    done = 0
    for gid in ids:
        try:
            done += 1 if import_game(gid) else 0
        except SystemExit as e:
            print(f'✗ {gid}: {e}')
        except Exception as e:  # keep going with the other games
            print(f'✗ {gid}: {e}')
    print(f'{done} game(s) imported. Restart the server to see them in the lobby.')


if __name__ == '__main__':
    main()
